/**
 * @file national-registry.ts
 * Catálogo Canônico Nacional de Órgãos, CETRANs/CONTRANDIFE e Estados do Brasil (27 UFs + Federal).
 * Única Fonte da Verdade (Single Source of Truth) para o Sistema Nacional de Monitoramento Jurídico-Operacional.
 */

import { KnowledgeOrgan, KnowledgeCetran, KnowledgeState } from './types';
import { SubmissionInstructions } from '../../types';

// ==========================================
// 1. TODAS AS 27 UNIDADES FEDERATIVAS (UFs)
// ==========================================
export const NATIONAL_STATES_DB: Record<string, KnowledgeState> = {
  AC: {
    uf: 'AC',
    name: 'Acre',
    region: 'Norte',
    capital: 'Rio Branco',
    detranId: 'DETRAN_AC',
    cetranId: 'CETRAN_AC',
    officialGovernmentPortal: 'https://www.ac.gov.br',
    serviceNetworkName: 'OCA - Organização em Centros de Atendimento',
    activeProceduresCount: 5,
  },
  AL: {
    uf: 'AL',
    name: 'Alagoas',
    region: 'Nordeste',
    capital: 'Maceió',
    detranId: 'DETRAN_AL',
    cetranId: 'CETRAN_AL',
    officialGovernmentPortal: 'https://www.al.gov.br',
    serviceNetworkName: 'Central Já!',
    activeProceduresCount: 5,
  },
  AP: {
    uf: 'AP',
    name: 'Amapá',
    region: 'Norte',
    capital: 'Macapá',
    detranId: 'DETRAN_AP',
    cetranId: 'CETRAN_AP',
    officialGovernmentPortal: 'https://www.ap.gov.br',
    serviceNetworkName: 'Super Fácil Amapá',
    activeProceduresCount: 5,
  },
  AM: {
    uf: 'AM',
    name: 'Amazonas',
    region: 'Norte',
    capital: 'Manaus',
    detranId: 'DETRAN_AM',
    cetranId: 'CETRAN_AM',
    officialGovernmentPortal: 'https://www.am.gov.br',
    serviceNetworkName: 'PAC - Pronto Atendimento ao Cidadão',
    activeProceduresCount: 5,
  },
  BA: {
    uf: 'BA',
    name: 'Bahia',
    region: 'Nordeste',
    capital: 'Salvador',
    detranId: 'DETRAN_BA',
    cetranId: 'CETRAN_BA',
    officialGovernmentPortal: 'https://www.ba.gov.br',
    serviceNetworkName: 'SAC - Serviço de Atendimento ao Cidadão',
    activeProceduresCount: 5,
  },
  CE: {
    uf: 'CE',
    name: 'Ceará',
    region: 'Nordeste',
    capital: 'Fortaleza',
    detranId: 'DETRAN_CE',
    cetranId: 'CETRAN_CE',
    officialGovernmentPortal: 'https://www.ce.gov.br',
    serviceNetworkName: 'Vapt Vupt Ceará / Casa do Cidadão',
    activeProceduresCount: 5,
  },
  DF: {
    uf: 'DF',
    name: 'Distrito Federal',
    region: 'Centro-Oeste',
    capital: 'Brasília',
    detranId: 'DETRAN_DF',
    cetranId: 'CONTRANDIFE_DF',
    officialGovernmentPortal: 'https://www.df.gov.br',
    serviceNetworkName: 'Na Hora DF',
    activeProceduresCount: 5,
  },
  ES: {
    uf: 'ES',
    name: 'Espírito Santo',
    region: 'Sudeste',
    capital: 'Vitória',
    detranId: 'DETRAN_ES',
    cetranId: 'CETRAN_ES',
    officialGovernmentPortal: 'https://www.es.gov.br',
    serviceNetworkName: 'Faça Fácil ES',
    activeProceduresCount: 5,
  },
  GO: {
    uf: 'GO',
    name: 'Goiás',
    region: 'Centro-Oeste',
    capital: 'Goiânia',
    detranId: 'DETRAN_GO',
    cetranId: 'CETRAN_GO',
    officialGovernmentPortal: 'https://www.go.gov.br',
    serviceNetworkName: 'Vapt Vupt Goiás',
    activeProceduresCount: 5,
  },
  MA: {
    uf: 'MA',
    name: 'Maranhão',
    region: 'Nordeste',
    capital: 'São Luís',
    detranId: 'DETRAN_MA',
    cetranId: 'CETRAN_MA',
    officialGovernmentPortal: 'https://www.ma.gov.br',
    serviceNetworkName: 'Viva Procon Maranhão',
    activeProceduresCount: 5,
  },
  MT: {
    uf: 'MT',
    name: 'Mato Grosso',
    region: 'Centro-Oeste',
    capital: 'Cuiabá',
    detranId: 'DETRAN_MT',
    cetranId: 'CETRAN_MT',
    officialGovernmentPortal: 'https://www.mt.gov.br',
    serviceNetworkName: 'Ganha Tempo MT',
    activeProceduresCount: 5,
  },
  MS: {
    uf: 'MS',
    name: 'Mato Grosso do Sul',
    region: 'Centro-Oeste',
    capital: 'Campo Grande',
    detranId: 'DETRAN_MS',
    cetranId: 'CETRAN_MS',
    officialGovernmentPortal: 'https://www.ms.gov.br',
    serviceNetworkName: 'Fácil MS',
    activeProceduresCount: 5,
  },
  MG: {
    uf: 'MG',
    name: 'Minas Gerais',
    region: 'Sudeste',
    capital: 'Belo Horizonte',
    detranId: 'DETRAN_MG',
    cetranId: 'CETRAN_MG',
    officialGovernmentPortal: 'https://www.mg.gov.br',
    serviceNetworkName: 'UAI - Unidade de Atendimento Integrado',
    activeProceduresCount: 5,
  },
  PA: {
    uf: 'PA',
    name: 'Pará',
    region: 'Norte',
    capital: 'Belém',
    detranId: 'DETRAN_PA',
    cetranId: 'CETRAN_PA',
    officialGovernmentPortal: 'https://www.pa.gov.br',
    serviceNetworkName: 'Estação Cidadania Pará',
    activeProceduresCount: 5,
  },
  PB: {
    uf: 'PB',
    name: 'Paraíba',
    region: 'Nordeste',
    capital: 'João Pessoa',
    detranId: 'DETRAN_PB',
    cetranId: 'CETRAN_PB',
    officialGovernmentPortal: 'https://www.pb.gov.br',
    serviceNetworkName: 'Casa da Cidadania Paraíba',
    activeProceduresCount: 5,
  },
  PR: {
    uf: 'PR',
    name: 'Paraná',
    region: 'Sul',
    capital: 'Curitiba',
    detranId: 'DETRAN_PR',
    cetranId: 'CETRAN_PR',
    officialGovernmentPortal: 'https://www.pr.gov.br',
    serviceNetworkName: 'Piá Paraná / Ciretrans',
    activeProceduresCount: 5,
  },
  PE: {
    uf: 'PE',
    name: 'Pernambuco',
    region: 'Nordeste',
    capital: 'Recife',
    detranId: 'DETRAN_PE',
    cetranId: 'CETRAN_PE',
    officialGovernmentPortal: 'https://www.pe.gov.br',
    serviceNetworkName: 'Expresso Cidadão Pernambuco',
    activeProceduresCount: 5,
  },
  PI: {
    uf: 'PI',
    name: 'Piauí',
    region: 'Nordeste',
    capital: 'Teresina',
    detranId: 'DETRAN_PI',
    cetranId: 'CETRAN_PI',
    officialGovernmentPortal: 'https://www.pi.gov.br',
    serviceNetworkName: 'Espaço Cidadania Piauí',
    activeProceduresCount: 5,
  },
  RJ: {
    uf: 'RJ',
    name: 'Rio de Janeiro',
    region: 'Sudeste',
    capital: 'Rio de Janeiro',
    detranId: 'DETRAN_RJ',
    cetranId: 'CETRAN_RJ',
    officialGovernmentPortal: 'https://www.rj.gov.br',
    serviceNetworkName: 'Poupatempo RJ / Postos DETRAN',
    activeProceduresCount: 5,
  },
  RN: {
    uf: 'RN',
    name: 'Rio Grande do Norte',
    region: 'Nordeste',
    capital: 'Natal',
    detranId: 'DETRAN_RN',
    cetranId: 'CETRAN_RN',
    officialGovernmentPortal: 'https://www.rn.gov.br',
    serviceNetworkName: 'Central do Cidadão RN',
    activeProceduresCount: 5,
  },
  RS: {
    uf: 'RS',
    name: 'Rio Grande do Sul',
    region: 'Sul',
    capital: 'Porto Alegre',
    detranId: 'DETRAN_RS',
    cetranId: 'CETRAN_RS',
    officialGovernmentPortal: 'https://www.rs.gov.br',
    serviceNetworkName: 'Tudo Fácil RS',
    activeProceduresCount: 5,
  },
  RO: {
    uf: 'RO',
    name: 'Rondônia',
    region: 'Norte',
    capital: 'Porto Velho',
    detranId: 'DETRAN_RO',
    cetranId: 'CETRAN_RO',
    officialGovernmentPortal: 'https://www.ro.gov.br',
    serviceNetworkName: 'Tudo Aqui Rondônia',
    activeProceduresCount: 5,
  },
  RR: {
    uf: 'RR',
    name: 'Roraima',
    region: 'Norte',
    capital: 'Boa Vista',
    detranId: 'DETRAN_RR',
    cetranId: 'CETRAN_RR',
    officialGovernmentPortal: 'https://www.rr.gov.br',
    serviceNetworkName: 'Casa do Cidadão Roraima',
    activeProceduresCount: 5,
  },
  SC: {
    uf: 'SC',
    name: 'Santa Catarina',
    region: 'Sul',
    capital: 'Florianópolis',
    detranId: 'DETRAN_SC',
    cetranId: 'CETRAN_SC',
    officialGovernmentPortal: 'https://www.sc.gov.br',
    serviceNetworkName: 'Pronto Atendimento SC / Ciretrans',
    activeProceduresCount: 5,
  },
  SP: {
    uf: 'SP',
    name: 'São Paulo',
    region: 'Sudeste',
    capital: 'São Paulo',
    detranId: 'DETRAN_SP',
    cetranId: 'CETRAN_SP',
    officialGovernmentPortal: 'https://www.sp.gov.br',
    serviceNetworkName: 'Poupatempo SP',
    activeProceduresCount: 5,
  },
  SE: {
    uf: 'SE',
    name: 'Sergipe',
    region: 'Nordeste',
    capital: 'Aracaju',
    detranId: 'DETRAN_SE',
    cetranId: 'CETRAN_SE',
    officialGovernmentPortal: 'https://www.se.gov.br',
    serviceNetworkName: 'Ceac - Centro de Atendimento ao Cidadão',
    activeProceduresCount: 5,
  },
  TO: {
    uf: 'TO',
    name: 'Tocantins',
    region: 'Norte',
    capital: 'Palmas',
    detranId: 'DETRAN_TO',
    cetranId: 'CETRAN_TO',
    officialGovernmentPortal: 'https://www.to.gov.br',
    serviceNetworkName: 'É Pra Já Tocantins',
    activeProceduresCount: 5,
  },
};

// ==========================================
// 2. TODOS OS ÓRGÃOS CANÔNICOS (27 DETRANs + FEDERAIS + DERs + CETs)
// ==========================================
export const NATIONAL_ORGANS_DB: KnowledgeOrgan[] = [
  // --- ÓRGÃOS FEDERAIS ---
  {
    id: 'PRF_BRASIL',
    code: '000100',
    name: 'Polícia Rodoviária Federal (Superintendência Nacional)',
    abbreviation: 'PRF',
    sphere: 'federal',
    state: 'FEDERAL',
    capital: 'Brasília',
    onlinePortalUrl: 'https://sistemas.prf.gov.br/portal/recursos',
    physicalAddress: 'Setor Policial Sul, Bloco C, Lote 5, Brasília/DF - CEP 70610-909',
    email: 'multas.sede@prf.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Nacional e Regionais da PRF nas Superintendências Estaduais',
    protocolChannels: {
      digitalPortalUrl: 'https://sistemas.prf.gov.br/portal/recursos',
      govBrAuthenticationRequired: true,
      postalAddress: 'Setor Policial Sul, Bloco C, Lote 5, Brasília/DF - CEP 70610-909',
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DNIT_FEDERAL',
    code: '000200',
    name: 'Departamento Nacional de Infraestrutura de Transportes',
    abbreviation: 'DNIT',
    sphere: 'federal',
    state: 'FEDERAL',
    capital: 'Brasília',
    onlinePortalUrl: 'https://servicos.dnit.gov.br/multas',
    physicalAddress: 'SAN Quadra 3, Bloco A, Ed. Núcleo dos Transportes, Brasília/DF - CEP 70040-902',
    email: 'recursos.dnit@dnit.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Especial do DNIT em Brasília/DF',
    protocolChannels: {
      digitalPortalUrl: 'https://servicos.dnit.gov.br/multas',
      govBrAuthenticationRequired: true,
      postalAddress: 'SAN Quadra 3, Bloco A, Ed. Núcleo dos Transportes, Brasília/DF - CEP 70040-902',
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 15,
    },
    validFrom: '2001-06-05',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'ANTT_FEDERAL',
    code: '000300',
    name: 'Agência Nacional de Transportes Terrestres',
    abbreviation: 'ANTT',
    sphere: 'federal',
    state: 'FEDERAL',
    capital: 'Brasília',
    onlinePortalUrl: 'https://www.gov.br/antt/pt-br/assuntos/passageiros/fiscalizacao-e-multas',
    physicalAddress: 'Setor de Clubes Esportivos Sul - SCES, Trecho 3, Lote 10, Brasília/DF - CEP 70200-003',
    email: 'multas@antt.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Comissão Especial de Julgamento de Recursos da ANTT',
    protocolChannels: {
      digitalPortalUrl: 'https://sistemas.antt.gov.br',
      govBrAuthenticationRequired: true,
      postalAddress: 'Setor de Clubes Esportivos Sul - SCES, Trecho 3, Lote 10, Brasília/DF - CEP 70200-003',
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '2001-06-05',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },

  // --- SUDESTE ---
  {
    id: 'DETRAN_SP',
    code: '126000',
    name: 'Departamento Estadual de Trânsito de São Paulo',
    abbreviation: 'DETRAN-SP',
    sphere: 'estadual',
    state: 'SP',
    capital: 'São Paulo',
    onlinePortalUrl: 'https://www.detran.sp.gov.br/servicos/recursos',
    physicalAddress: 'Rua Boa Vista, 209 - Centro, São Paulo/SP - CEP 01014-001',
    email: 'recursos@detran.sp.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Central do DETRAN-SP e JARI descentralizadas nas Ciretrans',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.sp.gov.br/servicos/recursos',
      presencialNetworkName: 'Postos Poupatempo em todo o Estado de São Paulo',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF', 'JPEG'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DER_SP',
    code: '126100',
    name: 'Departamento de Estradas de Rodagem de São Paulo',
    abbreviation: 'DER-SP',
    sphere: 'estadual',
    state: 'SP',
    capital: 'São Paulo',
    onlinePortalUrl: 'https://www.der.sp.gov.br/multas/recursos',
    physicalAddress: 'Ala Central, Av. do Estado, 777 - Bom Retiro, São Paulo/SP - CEP 01107-901',
    email: 'jari@der.sp.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Colegiados JARI DER-SP',
    protocolChannels: {
      digitalPortalUrl: 'https://www.der.sp.gov.br/multas/recursos',
      govBrAuthenticationRequired: true,
      postalAddress: 'Av. do Estado, 777 - Bom Retiro, São Paulo/SP - CEP 01107-901',
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'CET_SP',
    code: '271000',
    name: 'Companhia de Engenharia de Tráfego de São Paulo / DSV',
    abbreviation: 'CET-SP / DSV',
    sphere: 'municipal',
    state: 'SP',
    capital: 'São Paulo',
    onlinePortalUrl: 'https://dsv.prefeitura.sp.gov.br/defesa',
    physicalAddress: 'Rua Sumidouro, 740 - Pinheiros, São Paulo/SP - CEP 05428-010',
    email: 'dsveletronico@prefeitura.sp.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Juntas Administrativas da Secretaria Municipal de Mobilidade de SP',
    protocolChannels: {
      digitalPortalUrl: 'https://dsv.prefeitura.sp.gov.br/defesa',
      presencialNetworkName: 'Descomplica SP e Unidades DSV',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_RJ',
    code: '119000',
    name: 'Departamento Estadual de Trânsito do Rio de Janeiro',
    abbreviation: 'DETRAN-RJ',
    sphere: 'estadual',
    state: 'RJ',
    capital: 'Rio de Janeiro',
    onlinePortalUrl: 'https://www.detran.rj.gov.br/protocolo-defesas',
    physicalAddress: 'Av. Presidente Vargas, 817 - Centro, Rio de Janeiro/RJ - CEP 20071-004',
    email: 'jari@detran.rj.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Comissões de Julgamento da JARI DETRAN-RJ',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.rj.gov.br/protocolo-defesas',
      presencialNetworkName: 'Postos de Atendimento DETRAN-RJ e Poupatempo RJ',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_MG',
    code: '113000',
    name: 'Departamento Estadual de Trânsito de Minas Gerais',
    abbreviation: 'DETRAN-MG',
    sphere: 'estadual',
    state: 'MG',
    capital: 'Belo Horizonte',
    onlinePortalUrl: 'https://www.detran.mg.gov.br/infracoes/recursos',
    physicalAddress: 'Av. João Pinheiro, 417 - Boa Viagem, Belo Horizonte/MG - CEP 30130-180',
    email: 'jari.mg@policiacivil.mg.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Colegiados JARI DETRAN-MG',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.mg.gov.br/infracoes/recursos',
      presencialNetworkName: 'Unidades de Atendimento Integrado (UAI Minas)',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_ES',
    code: '108000',
    name: 'Departamento Estadual de Trânsito do Espírito Santo',
    abbreviation: 'DETRAN-ES',
    sphere: 'estadual',
    state: 'ES',
    capital: 'Vitória',
    onlinePortalUrl: 'https://detran.es.gov.br/recursos-de-infracoes',
    physicalAddress: 'Av. Fernando Ferrari, 1080 - Ed. América Centro Empresarial, Vitória/ES - CEP 29075-010',
    email: 'jari@detran.es.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Central do DETRAN-ES',
    protocolChannels: {
      digitalPortalUrl: 'https://detran.es.gov.br/recursos-de-infracoes',
      presencialNetworkName: 'Agências Faça Fácil Cariacica e Ciretrans',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },

  // --- SUL ---
  {
    id: 'DETRAN_PR',
    code: '116000',
    name: 'Departamento de Trânsito do Paraná',
    abbreviation: 'DETRAN-PR',
    sphere: 'estadual',
    state: 'PR',
    capital: 'Curitiba',
    onlinePortalUrl: 'https://www.detran.pr.gov.br/servicos/recursos',
    physicalAddress: 'Av. Victor Ferreira do Amaral, 2940 - Tarumã, Curitiba/PR - CEP 82800-900',
    email: 'recursos@detran.pr.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Juntas Administrativas de Recursos de Infrações do DETRAN-PR',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.pr.gov.br/servicos/recursos',
      mobileAppName: 'Detran Inteligente PR',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_SC',
    code: '124000',
    name: 'Departamento Estadual de Trânsito de Santa Catarina',
    abbreviation: 'DETRAN-SC',
    sphere: 'estadual',
    state: 'SC',
    capital: 'Florianópolis',
    onlinePortalUrl: 'https://www.detran.sc.gov.br/infracoes/recursos',
    physicalAddress: 'Rua Ursulina de Senna Castro, 226 - Estreito, Florianópolis/SC - CEP 88070-290',
    email: 'jari@detran.sc.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Colegiados JARI DETRAN-SC',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.sc.gov.br/infracoes/recursos',
      mobileAppName: 'Detran Digital SC',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_RS',
    code: '123000',
    name: 'Departamento Estadual de Trânsito do Rio Grande do Sul',
    abbreviation: 'DETRAN-RS',
    sphere: 'estadual',
    state: 'RS',
    capital: 'Porto Alegre',
    onlinePortalUrl: 'https://www.detran.rs.gov.br/infracoes-e-recursos',
    physicalAddress: 'Rua Voluntários da Pátria, 1358 - Centro, Porto Alegre/RS - CEP 90230-010',
    email: 'recursos@detran.rs.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Estadual DETRAN-RS',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.rs.gov.br/infracoes-e-recursos',
      presencialNetworkName: 'Unidades Tudo Fácil RS e Centros de Registro de Veículos (CRVAs)',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },

  // --- DISTRITO FEDERAL & CENTRO-OESTE ---
  {
    id: 'DETRAN_DF',
    code: '107000',
    name: 'Departamento de Trânsito do Distrito Federal',
    abbreviation: 'DETRAN-DF',
    sphere: 'distrital',
    state: 'DF',
    capital: 'Brasília',
    onlinePortalUrl: 'https://www.detran.df.gov.br/infracoes/recursos',
    physicalAddress: 'SAM Lote A Bloco B - Edifício Sede do DETRAN-DF, Brasília/DF - CEP 70620-000',
    email: 'jari@detran.df.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI do DETRAN-DF',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.df.gov.br/infracoes/recursos',
      mobileAppName: 'Detran Digital DF',
      presencialNetworkName: 'Postos Na Hora DF',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_GO',
    code: '109000',
    name: 'Departamento Estadual de Trânsito de Goiás',
    abbreviation: 'DETRAN-GO',
    sphere: 'estadual',
    state: 'GO',
    capital: 'Goiânia',
    onlinePortalUrl: 'https://www.detran.go.gov.br/servicos/recursos',
    physicalAddress: 'Av. Engenheiro Atílio Correia Lima, 1875 - Cidade Jardim, Goiânia/GO - CEP 74425-030',
    email: 'jari@detran.go.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'Juntas Administrativas de Recursos de Goiás (JARI DETRAN-GO)',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.go.gov.br/servicos/recursos',
      presencialNetworkName: 'Vapt Vupt Goiás',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_MT',
    code: '111000',
    name: 'Departamento Estadual de Trânsito de Mato Grosso',
    abbreviation: 'DETRAN-MT',
    sphere: 'estadual',
    state: 'MT',
    capital: 'Cuiabá',
    onlinePortalUrl: 'https://www.detran.mt.gov.br/recursos',
    physicalAddress: 'Av. Doutor Hélio Ribeiro, 1000 - Centro Político Administrativo, Cuiabá/MT - CEP 78048-910',
    email: 'jari@detran.mt.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Estadual DETRAN-MT',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.mt.gov.br/recursos',
      presencialNetworkName: 'Ganha Tempo MT',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_MS',
    code: '112000',
    name: 'Departamento Estadual de Trânsito de Mato Grosso do Sul',
    abbreviation: 'DETRAN-MS',
    sphere: 'estadual',
    state: 'MS',
    capital: 'Campo Grande',
    onlinePortalUrl: 'https://www.detran.ms.gov.br/infracoes/recursos',
    physicalAddress: 'Rodovia MS-080, Km 10, s/n - Campo Grande/MS - CEP 79114-901',
    email: 'recursos@detran.ms.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Central DETRAN-MS',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.ms.gov.br/infracoes/recursos',
      presencialNetworkName: 'Agências Fácil MS',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },

  // --- NORDESTE ---
  {
    id: 'DETRAN_BA',
    code: '105000',
    name: 'Departamento Estadual de Trânsito da Bahia',
    abbreviation: 'DETRAN-BA',
    sphere: 'estadual',
    state: 'BA',
    capital: 'Salvador',
    onlinePortalUrl: 'https://www.detran.ba.gov.br/servicos/recursos',
    physicalAddress: 'Av. Antônio Carlos Magalhães, 7744 - Iguatemi, Salvador/BA - CEP 41110-700',
    email: 'jari@detran.ba.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-BA',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.ba.gov.br/servicos/recursos',
      presencialNetworkName: 'Postos SAC Bahia',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_PE',
    code: '117000',
    name: 'Departamento Estadual de Trânsito de Pernambuco',
    abbreviation: 'DETRAN-PE',
    sphere: 'estadual',
    state: 'PE',
    capital: 'Recife',
    onlinePortalUrl: 'https://www.detran.pe.gov.br/infracoes/recursos',
    physicalAddress: 'Estrada do Barbalho, 889 - Iputinga, Recife/PE - CEP 50690-900',
    email: 'jari@detran.pe.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI Estadual DETRAN-PE',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.pe.gov.br/infracoes/recursos',
      presencialNetworkName: 'Expresso Cidadão Pernambuco',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_CE',
    code: '106000',
    name: 'Departamento Estadual de Trânsito do Ceará',
    abbreviation: 'DETRAN-CE',
    sphere: 'estadual',
    state: 'CE',
    capital: 'Fortaleza',
    onlinePortalUrl: 'https://www.detran.ce.gov.br/servicos/recursos',
    physicalAddress: 'Av. Godofredo Maciel, 2900 - Maraponga, Fortaleza/CE - CEP 60710-903',
    email: 'jari@detran.ce.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-CE',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.ce.gov.br/servicos/recursos',
      presencialNetworkName: 'Vapt Vupt Ceará / Casa do Cidadão',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_MA',
    code: '110000',
    name: 'Departamento Estadual de Trânsito do Maranhão',
    abbreviation: 'DETRAN-MA',
    sphere: 'estadual',
    state: 'MA',
    capital: 'São Luís',
    onlinePortalUrl: 'https://www.detran.ma.gov.br/recursos',
    physicalAddress: 'Av. dos Franceses, s/n - Vila Palmeira, São Luís/MA - CEP 65036-284',
    email: 'jari@detran.ma.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-MA',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.ma.gov.br/recursos',
      presencialNetworkName: 'Viva Procon Maranhão',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_PB',
    code: '115000',
    name: 'Departamento Estadual de Trânsito da Paraíba',
    abbreviation: 'DETRAN-PB',
    sphere: 'estadual',
    state: 'PB',
    capital: 'João Pessoa',
    onlinePortalUrl: 'https://detran.pb.gov.br/servicos/recursos',
    physicalAddress: 'Rua Emília Batista Celani, s/n - Mangabeira VII, João Pessoa/PB - CEP 58058-280',
    email: 'jari@detran.pb.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-PB',
    protocolChannels: {
      digitalPortalUrl: 'https://detran.pb.gov.br/servicos/recursos',
      presencialNetworkName: 'Casas da Cidadania Paraíba',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_RN',
    code: '120000',
    name: 'Departamento Estadual de Trânsito do Rio Grande do Norte',
    abbreviation: 'DETRAN-RN',
    sphere: 'estadual',
    state: 'RN',
    capital: 'Natal',
    onlinePortalUrl: 'https://www.detran.rn.gov.br/recursos',
    physicalAddress: 'Av. Perimetral Leste, 113 - Cidade da Esperança, Natal/RN - CEP 59070-400',
    email: 'jari@detran.rn.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-RN',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.rn.gov.br/recursos',
      presencialNetworkName: 'Central do Cidadão RN',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_AL',
    code: '102000',
    name: 'Departamento Estadual de Trânsito de Alagoas',
    abbreviation: 'DETRAN-AL',
    sphere: 'estadual',
    state: 'AL',
    capital: 'Maceió',
    onlinePortalUrl: 'https://www.detran.al.gov.br/servicos/recursos',
    physicalAddress: 'Av. Menino Marcelo, s/n - Cidade Universitária, Maceió/AL - CEP 57073-470',
    email: 'jari@detran.al.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-AL',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.al.gov.br/servicos/recursos',
      presencialNetworkName: 'Centrais Já! Alagoas',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_SE',
    code: '125000',
    name: 'Departamento Estadual de Trânsito de Sergipe',
    abbreviation: 'DETRAN-SE',
    sphere: 'estadual',
    state: 'SE',
    capital: 'Aracaju',
    onlinePortalUrl: 'https://www.detran.se.gov.br/recursos',
    physicalAddress: 'Av. Tancredo Neves, s/n - Ponto Novo, Aracaju/SE - CEP 49097-510',
    email: 'jari@detran.se.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-SE',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.se.gov.br/recursos',
      presencialNetworkName: 'Ceac Sergipe',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_PI',
    code: '118000',
    name: 'Departamento Estadual de Trânsito do Piauí',
    abbreviation: 'DETRAN-PI',
    sphere: 'estadual',
    state: 'PI',
    capital: 'Teresina',
    onlinePortalUrl: 'https://www.detran.pi.gov.br/recursos',
    physicalAddress: 'Av. Gil Martins, 2000 - Redenção, Teresina/PI - CEP 64017-810',
    email: 'jari@detran.pi.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-PI',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.pi.gov.br/recursos',
      presencialNetworkName: 'Espaço Cidadania Piauí',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },

  // --- NORTE ---
  {
    id: 'DETRAN_AM',
    code: '104000',
    name: 'Departamento Estadual de Trânsito do Amazonas',
    abbreviation: 'DETRAN-AM',
    sphere: 'estadual',
    state: 'AM',
    capital: 'Manaus',
    onlinePortalUrl: 'https://www.detran.am.gov.br/servicos/recursos',
    physicalAddress: 'Av. Mário Ypiranga Monteiro, 2884 - Parque 10 de Novembro, Manaus/AM - CEP 69050-030',
    email: 'jari@detran.am.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-AM',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.am.gov.br/servicos/recursos',
      presencialNetworkName: 'PAC Amazonas',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_PA',
    code: '114000',
    name: 'Departamento de Trânsito do Estado do Pará',
    abbreviation: 'DETRAN-PA',
    sphere: 'estadual',
    state: 'PA',
    capital: 'Belém',
    onlinePortalUrl: 'https://www.detran.pa.gov.br/recursos',
    physicalAddress: 'Av. Augusto Montenegro, Km 03, s/n - Mangueirão, Belém/PA - CEP 66640-000',
    email: 'jari@detran.pa.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-PA',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.pa.gov.br/recursos',
      presencialNetworkName: 'Estação Cidadania Pará',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_RO',
    code: '121000',
    name: 'Departamento Estadual de Trânsito de Rondônia',
    abbreviation: 'DETRAN-RO',
    sphere: 'estadual',
    state: 'RO',
    capital: 'Porto Velho',
    onlinePortalUrl: 'https://www.detran.ro.gov.br/recursos',
    physicalAddress: 'Rua Doutor José Adelino, 4477 - Costa e Silva, Porto Velho/RO - CEP 76803-592',
    email: 'jari@detran.ro.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-RO',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.ro.gov.br/recursos',
      presencialNetworkName: 'Tudo Aqui Rondônia',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_TO',
    code: '127000',
    name: 'Departamento Estadual de Trânsito do Tocantins',
    abbreviation: 'DETRAN-TO',
    sphere: 'estadual',
    state: 'TO',
    capital: 'Palmas',
    onlinePortalUrl: 'https://www.detran.to.gov.br/recursos',
    physicalAddress: 'Quadra 401 Norte, Av. NS 01, Lote 02 - Plano Diretor Norte, Palmas/TO - CEP 77006-444',
    email: 'jari@detran.to.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-TO',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.to.gov.br/recursos',
      presencialNetworkName: 'É Pra Já Tocantins',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_AC',
    code: '101000',
    name: 'Departamento Estadual de Trânsito do Acre',
    abbreviation: 'DETRAN-AC',
    sphere: 'estadual',
    state: 'AC',
    capital: 'Rio Branco',
    onlinePortalUrl: 'https://www.detran.ac.gov.br/recursos',
    physicalAddress: 'Estrada Dias Martins, 894 - Jardim Primavera, Rio Branco/AC - CEP 69919-278',
    email: 'jari@detran.ac.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-AC',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.ac.gov.br/recursos',
      presencialNetworkName: 'OCA - Organização em Centros de Atendimento',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_AP',
    code: '103000',
    name: 'Departamento Estadual de Trânsito do Amapá',
    abbreviation: 'DETRAN-AP',
    sphere: 'estadual',
    state: 'AP',
    capital: 'Macapá',
    onlinePortalUrl: 'https://www.detran.ap.gov.br/recursos',
    physicalAddress: 'Rua Tancredo Neves, 217 - São Lázaro, Macapá/AP - CEP 68908-450',
    email: 'jari@detran.ap.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-AP',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.ap.gov.br/recursos',
      presencialNetworkName: 'Super Fácil Amapá',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
  {
    id: 'DETRAN_RR',
    code: '122000',
    name: 'Departamento Estadual de Trânsito de Roraima',
    abbreviation: 'DETRAN-RR',
    sphere: 'estadual',
    state: 'RR',
    capital: 'Boa Vista',
    onlinePortalUrl: 'https://www.detran.rr.gov.br/recursos',
    physicalAddress: 'Av. Brigadeiro Eduardo Gomes, 4214 - Aeroporto, Boa Vista/RR - CEP 69310-005',
    email: 'jari@detran.rr.gov.br',
    standardDeadlineDays: 30,
    jariStructure: 'JARI DETRAN-RR',
    protocolChannels: {
      digitalPortalUrl: 'https://www.detran.rr.gov.br/recursos',
      presencialNetworkName: 'Casa do Cidadão Roraima',
      govBrAuthenticationRequired: true,
      acceptedFormats: ['PDF'],
      maxFileSizeMb: 10,
    },
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
    version: 1,
    lastVerifiedAt: '2026-08-29',
  },
];

// ==========================================
// 3. TODOS OS CETRANs (26 Estados) + CONTRANDIFE (DF) + CONTRAN (Federal)
// ==========================================
export const NATIONAL_CETRANS_DB: KnowledgeCetran[] = [
  {
    id: 'CONTRANDIFE_DF',
    uf: 'DF',
    name: 'Conselho de Trânsito do Distrito Federal (CONTRANDIFE)',
    sphere: 'distrital',
    presidentOrBoard: 'Conselho Pleno do CONTRANDIFE',
    address: 'SAM Lote A Bloco B - Edifício Sede do DETRAN-DF, Brasília/DF',
    portalUrl: 'https://www.contrandife.df.gov.br',
    isContrandife: true,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_SP',
    uf: 'SP',
    name: 'Conselho Estadual de Trânsito de São Paulo (CETRAN-SP)',
    sphere: 'estadual',
    presidentOrBoard: 'Presidência e Colegiado do CETRAN-SP',
    address: 'Rua Boa Vista, 209 - 6º andar - Centro, São Paulo/SP - CEP 01014-001',
    portalUrl: 'https://www.cetran.sp.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_RJ',
    uf: 'RJ',
    name: 'Conselho Estadual de Trânsito do Rio de Janeiro (CETRAN-RJ)',
    sphere: 'estadual',
    presidentOrBoard: 'Plenário do CETRAN-RJ',
    address: 'Av. Presidente Vargas, 817 - 10º andar - Centro, Rio de Janeiro/RJ',
    portalUrl: 'https://www.cetran.rj.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_MG',
    uf: 'MG',
    name: 'Conselho Estadual de Trânsito de Minas Gerais (CETRAN-MG)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras Recursais do CETRAN-MG',
    address: 'Rodovia Papa João Paulo II, 4001 - Edifício Gerais, Belo Horizonte/MG',
    portalUrl: 'https://www.cetran.mg.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_ES',
    uf: 'ES',
    name: 'Conselho Estadual de Trânsito do Espírito Santo (CETRAN-ES)',
    sphere: 'estadual',
    presidentOrBoard: 'Colegiado do CETRAN-ES',
    address: 'Av. Fernando Ferrari, 1080 - Vitória/ES',
    portalUrl: 'https://cetran.es.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_PR',
    uf: 'PR',
    name: 'Conselho Estadual de Trânsito do Paraná (CETRAN-PR)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras de Julgamento do CETRAN-PR',
    address: 'Av. Victor Ferreira do Amaral, 2940 - Curitiba/PR',
    portalUrl: 'https://www.cetran.pr.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_SC',
    uf: 'SC',
    name: 'Conselho Estadual de Trânsito de Santa Catarina (CETRAN-SC)',
    sphere: 'estadual',
    presidentOrBoard: 'Conselho Estadual CETRAN-SC',
    address: 'Rua Ursulina de Senna Castro, 226 - Florianópolis/SC',
    portalUrl: 'https://www.cetran.sc.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_RS',
    uf: 'RS',
    name: 'Conselho Estadual de Trânsito do Rio Grande do Sul (CETRAN-RS)',
    sphere: 'estadual',
    presidentOrBoard: 'Colegiado do CETRAN-RS',
    address: 'Rua Voluntários da Pátria, 1358 - Porto Alegre/RS',
    portalUrl: 'https://www.cetran.rs.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_BA',
    uf: 'BA',
    name: 'Conselho Estadual de Trânsito da Bahia (CETRAN-BA)',
    sphere: 'estadual',
    presidentOrBoard: 'Pleno do CETRAN-BA',
    address: 'Av. Antônio Carlos Magalhães, 7744 - Salvador/BA',
    portalUrl: 'https://www.cetran.ba.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_PE',
    uf: 'PE',
    name: 'Conselho Estadual de Trânsito de Pernambuco (CETRAN-PE)',
    sphere: 'estadual',
    presidentOrBoard: 'Conselho Estadual CETRAN-PE',
    address: 'Estrada do Barbalho, 889 - Recife/PE',
    portalUrl: 'https://www.cetran.pe.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_CE',
    uf: 'CE',
    name: 'Conselho Estadual de Trânsito do Ceará (CETRAN-CE)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras Recursais do CETRAN-CE',
    address: 'Av. Godofredo Maciel, 2900 - Fortaleza/CE',
    portalUrl: 'https://www.cetran.ce.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_GO',
    uf: 'GO',
    name: 'Conselho Estadual de Trânsito de Goiás (CETRAN-GO)',
    sphere: 'estadual',
    presidentOrBoard: 'Colegiado do CETRAN-GO',
    address: 'Av. Engenheiro Atílio Correia Lima, 1875 - Goiânia/GO',
    portalUrl: 'https://www.cetran.go.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_MT',
    uf: 'MT',
    name: 'Conselho Estadual de Trânsito de Mato Grosso (CETRAN-MT)',
    sphere: 'estadual',
    presidentOrBoard: 'Conselho Estadual CETRAN-MT',
    address: 'Av. Doutor Hélio Ribeiro, 1000 - Cuiabá/MT',
    portalUrl: 'https://www.cetran.mt.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_MS',
    uf: 'MS',
    name: 'Conselho Estadual de Trânsito de Mato Grosso do Sul (CETRAN-MS)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras de Recursos do CETRAN-MS',
    address: 'Rodovia MS-080, Km 10 - Campo Grande/MS',
    portalUrl: 'https://www.cetran.ms.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_MA',
    uf: 'MA',
    name: 'Conselho Estadual de Trânsito do Maranhão (CETRAN-MA)',
    sphere: 'estadual',
    presidentOrBoard: 'Pleno do CETRAN-MA',
    address: 'Av. dos Franceses, s/n - São Luís/MA',
    portalUrl: 'https://www.cetran.ma.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_PB',
    uf: 'PB',
    name: 'Conselho Estadual de Trânsito da Paraíba (CETRAN-PB)',
    sphere: 'estadual',
    presidentOrBoard: 'Colegiado do CETRAN-PB',
    address: 'Rua Emília Batista Celani, s/n - João Pessoa/PB',
    portalUrl: 'https://cetran.pb.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_RN',
    uf: 'RN',
    name: 'Conselho Estadual de Trânsito do Rio Grande do Norte (CETRAN-RN)',
    sphere: 'estadual',
    presidentOrBoard: 'Conselho Pleno CETRAN-RN',
    address: 'Av. Perimetral Leste, 113 - Natal/RN',
    portalUrl: 'https://www.cetran.rn.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_AL',
    uf: 'AL',
    name: 'Conselho Estadual de Trânsito de Alagoas (CETRAN-AL)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras Recursais do CETRAN-AL',
    address: 'Av. Menino Marcelo, s/n - Maceió/AL',
    portalUrl: 'https://cetran.al.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_SE',
    uf: 'SE',
    name: 'Conselho Estadual de Trânsito de Sergipe (CETRAN-SE)',
    sphere: 'estadual',
    presidentOrBoard: 'Colegiado do CETRAN-SE',
    address: 'Av. Tancredo Neves, s/n - Aracaju/SE',
    portalUrl: 'https://cetran.se.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_PI',
    uf: 'PI',
    name: 'Conselho Estadual de Trânsito do Piauí (CETRAN-PI)',
    sphere: 'estadual',
    presidentOrBoard: 'Conselho Estadual CETRAN-PI',
    address: 'Av. Gil Martins, 2000 - Teresina/PI',
    portalUrl: 'https://cetran.pi.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_AM',
    uf: 'AM',
    name: 'Conselho Estadual de Trânsito do Amazonas (CETRAN-AM)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras Recursais do CETRAN-AM',
    address: 'Av. Mário Ypiranga Monteiro, 2884 - Manaus/AM',
    portalUrl: 'https://www.cetran.am.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_PA',
    uf: 'PA',
    name: 'Conselho Estadual de Trânsito do Pará (CETRAN-PA)',
    sphere: 'estadual',
    presidentOrBoard: 'Colegiado do CETRAN-PA',
    address: 'Av. Augusto Montenegro, Km 03 - Belém/PA',
    portalUrl: 'https://www.cetran.pa.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_RO',
    uf: 'RO',
    name: 'Conselho Estadual de Trânsito de Rondônia (CETRAN-RO)',
    sphere: 'estadual',
    presidentOrBoard: 'Conselho Pleno CETRAN-RO',
    address: 'Rua Doutor José Adelino, 4477 - Porto Velho/RO',
    portalUrl: 'https://www.cetran.ro.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_TO',
    uf: 'TO',
    name: 'Conselho Estadual de Trânsito do Tocantins (CETRAN-TO)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras de Julgamento do CETRAN-TO',
    address: 'Quadra 401 Norte, Av. NS 01 - Palmas/TO',
    portalUrl: 'https://www.cetran.to.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_AC',
    uf: 'AC',
    name: 'Conselho Estadual de Trânsito do Acre (CETRAN-AC)',
    sphere: 'estadual',
    presidentOrBoard: 'Colegiado do CETRAN-AC',
    address: 'Estrada Dias Martins, 894 - Rio Branco/AC',
    portalUrl: 'https://www.cetran.ac.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_AP',
    uf: 'AP',
    name: 'Conselho Estadual de Trânsito do Amapá (CETRAN-AP)',
    sphere: 'estadual',
    presidentOrBoard: 'Conselho Estadual CETRAN-AP',
    address: 'Rua Tancredo Neves, 217 - Macapá/AP',
    portalUrl: 'https://www.cetran.ap.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
  {
    id: 'CETRAN_RR',
    uf: 'RR',
    name: 'Conselho Estadual de Trânsito de Roraima (CETRAN-RR)',
    sphere: 'estadual',
    presidentOrBoard: 'Câmaras Recursais do CETRAN-RR',
    address: 'Av. Brigadeiro Eduardo Gomes, 4214 - Boa Vista/RR',
    portalUrl: 'https://www.cetran.rr.gov.br',
    isContrandife: false,
    validFrom: '1998-01-22',
    validUntil: null,
    isActive: true,
  },
];

// ==========================================
// 4. MÉTODOS DETERMINÍSTICOS DE CONSULTA
// ==========================================

export function getAllNationalStates(): KnowledgeState[] {
  return Object.values(NATIONAL_STATES_DB);
}

export function getAllNationalOrgans(): KnowledgeOrgan[] {
  return NATIONAL_ORGANS_DB;
}

export function getAllNationalCetrans(): KnowledgeCetran[] {
  return NATIONAL_CETRANS_DB;
}

export function getStateInfo(uf: string): KnowledgeState | null {
  if (!uf) return null;
  const upper = uf.toUpperCase().trim();
  return NATIONAL_STATES_DB[upper] || null;
}

export const getNationalStateByUf = getStateInfo;

export function getNationalOrganById(id: string): KnowledgeOrgan | null {
  if (!id) return null;
  return NATIONAL_ORGANS_DB.find((o) => o.id === id) || null;
}

export function getNationalOrganByAbbreviation(abbreviation: string): KnowledgeOrgan | null {
  if (!abbreviation) return null;
  const clean = abbreviation.trim().toUpperCase();
  return (
    NATIONAL_ORGANS_DB.find(
      (o) =>
        o.abbreviation.toUpperCase() === clean ||
        o.id.toUpperCase() === clean ||
        o.code === clean
    ) || null
  );
}

export function getNationalOrganByState(uf: string): KnowledgeOrgan | null {
  if (!uf) return null;
  const clean = uf.toUpperCase().trim();
  return (
    NATIONAL_ORGANS_DB.find((o) => o.state === clean && (o.sphere === 'estadual' || o.sphere === 'distrital' || o.abbreviation.startsWith('DETRAN'))) ||
    NATIONAL_ORGANS_DB.find((o) => o.state === clean) ||
    null
  );
}

export function getCetranByState(uf: string): KnowledgeCetran | null {
  if (!uf) return null;
  const clean = uf.toUpperCase().trim();
  return NATIONAL_CETRANS_DB.find((c) => c.uf === clean) || null;
}

/**
 * Resolve protocolo e instruções de envio canônicas para qualquer órgão ou UF.
 */
export function resolveNationalProtocol(
  autuadorAbbreviationOrCode: string,
  _dateContext?: string
): SubmissionInstructions | null {
  if (!autuadorAbbreviationOrCode) return null;
  
  const organ = getNationalOrganByAbbreviation(autuadorAbbreviationOrCode);
  if (!organ) return null;

  const date = new Date();
  date.setDate(date.getDate() + (organ.standardDeadlineDays || 30));
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  const deadlineDate = `${day}/${month}/${year}`;

  return {
    competentBody: organ.jariStructure,
    recommendedMethod: 'portal_online',
    portalUrl: organ.onlinePortalUrl,
    physicalAddress: organ.physicalAddress,
    instructionsText: `Protocolo via ${organ.onlinePortalUrl} ou presencial em ${organ.physicalAddress}`,
    deadlineDate,
  };
}
