/**
 * @file sources-registry.ts
 * Catálogo Canônico de Fontes Oficiais de Monitoramento para o Brasil (27 UFs + Federal)
 * Tiers 1, 2, 3 com URLs oficiais e mapeamento por competência.
 */

import { KnowledgeSource } from './types';

export const OFFICIAL_SOURCES_REGISTRY: KnowledgeSource[] = [
  // ==========================================
  // FEDERAL / NACIONAL (Tier 1 & Tier 3)
  // ==========================================
  {
    id: 'SRC_FED_PLANALTO_CTB',
    uf: 'FEDERAL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'Planalto - Código de Trânsito Brasileiro (Lei 9.503/1997)',
    url: 'https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm',
    category: 'legislation',
    isActive: true,
  },
  {
    id: 'SRC_FED_SENATRAN_PORTAL',
    uf: 'FEDERAL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'Secretaria Nacional de Trânsito (SENATRAN)',
    url: 'https://www.gov.br/transportes/pt-br/assuntos/transito/senatran',
    category: 'legislation',
    isActive: true,
  },
  {
    id: 'SRC_FED_CONTRAN_RESOLUCOES',
    uf: 'FEDERAL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'Conselho Nacional de Trânsito (CONTRAN) - Resoluções',
    url: 'https://www.gov.br/transportes/pt-br/assuntos/transito/senatran/contran',
    category: 'legislation',
    isActive: true,
  },
  {
    id: 'SRC_FED_PRF_PORTAL',
    uf: 'FEDERAL',
    organId: 'PRF_BRASIL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'Polícia Rodoviária Federal - Portal de Multas e Recursos',
    url: 'https://sistemas.prf.gov.br/portal/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_FED_DNIT_PORTAL',
    uf: 'FEDERAL',
    organId: 'DNIT_FEDERAL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DNIT - Portal de Multas e Defesas',
    url: 'https://servicos.dnit.gov.br/multas',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_FED_ANTT_PORTAL',
    uf: 'FEDERAL',
    organId: 'ANTT_FEDERAL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'ANTT - Agência Nacional de Transportes Terrestres',
    url: 'https://www.gov.br/antt/pt-br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_FED_INMETRO_RADARES',
    uf: 'FEDERAL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'INMETRO - PSIQ Consulta de Radares e Cronotacógrafos',
    url: 'https://cronotacografo.rbmlq.gov.br/certificados/consultar',
    category: 'metrologia',
    isActive: true,
  },
  {
    id: 'SRC_FED_DOU',
    uf: 'FEDERAL',
    tier: 'TIER_2_OFFICIAL_GAZETTE',
    title: 'Diário Oficial da União (Imprensa Nacional)',
    url: 'https://www.in.gov.br/leiturajornal',
    category: 'diario_oficial',
    isActive: true,
  },
  {
    id: 'SRC_FED_STJ_JURISPRUDENCIA',
    uf: 'FEDERAL',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'STJ - Jurisprudência em Teses - Direito de Trânsito',
    url: 'https://scon.stj.jus.br/SCON/',
    category: 'jurisprudencia',
    isActive: true,
  },

  // ==========================================
  // SUDESTE (SP, RJ, MG, ES)
  // ==========================================
  {
    id: 'SRC_DETRAN_SP',
    uf: 'SP',
    organId: 'DETRAN_SP',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-SP - Protocolo Eletrônico de Recursos e Defesas',
    url: 'https://www.detran.sp.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_SP',
    uf: 'SP',
    organId: 'CETRAN_SP',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-SP - Conselho Estadual de Trânsito de São Paulo',
    url: 'https://www.cetran.sp.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DER_SP',
    uf: 'SP',
    organId: 'DER_SP',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DER-SP - Departamento de Estradas de Rodagem de SP',
    url: 'https://www.der.sp.gov.br/multas/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CET_SP',
    uf: 'SP',
    organId: 'CET_SP',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'CET / DSV São Paulo - Defesa da Autuação e Recursos JARI',
    url: 'https://dsv.prefeitura.sp.gov.br/defesa',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_RJ',
    uf: 'RJ',
    organId: 'DETRAN_RJ',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-RJ - Protocolo Geral e Defesa Prévia',
    url: 'https://www.detran.rj.gov.br/protocolo-defesas',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_RJ',
    uf: 'RJ',
    organId: 'CETRAN_RJ',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-RJ - Conselho Estadual de Trânsito do Rio de Janeiro',
    url: 'https://www.cetran.rj.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_MG',
    uf: 'MG',
    organId: 'DETRAN_MG',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-MG - Infrações e Recursos Online',
    url: 'https://www.detran.mg.gov.br/infracoes/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_MG',
    uf: 'MG',
    organId: 'CETRAN_MG',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-MG - Conselho Estadual de Trânsito de Minas Gerais',
    url: 'https://www.cetran.mg.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_ES',
    uf: 'ES',
    organId: 'DETRAN_ES',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-ES - Portal de Serviços e Defesa de Multas',
    url: 'https://detran.es.gov.br/recursos-de-infracoes',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_ES',
    uf: 'ES',
    organId: 'CETRAN_ES',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-ES - Conselho Estadual de Trânsito do Espírito Santo',
    url: 'https://cetran.es.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },

  // ==========================================
  // SUL (PR, SC, RS)
  // ==========================================
  {
    id: 'SRC_DETRAN_PR',
    uf: 'PR',
    organId: 'DETRAN_PR',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-PR - Recursos e Defesa Prévia Online',
    url: 'https://www.detran.pr.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_PR',
    uf: 'PR',
    organId: 'CETRAN_PR',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-PR - Conselho Estadual de Trânsito do Paraná',
    url: 'https://www.cetran.pr.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_SC',
    uf: 'SC',
    organId: 'DETRAN_SC',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-SC - Portal Digital de Multas e JARI',
    url: 'https://www.detran.sc.gov.br/infracoes/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_SC',
    uf: 'SC',
    organId: 'CETRAN_SC',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-SC - Conselho Estadual de Trânsito de Santa Catarina',
    url: 'https://www.cetran.sc.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_RS',
    uf: 'RS',
    organId: 'DETRAN_RS',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-RS - Central de Serviços e Apresentação de Defesas',
    url: 'https://www.detran.rs.gov.br/infracoes-e-recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_RS',
    uf: 'RS',
    organId: 'CETRAN_RS',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-RS - Conselho Estadual de Trânsito do Rio Grande do Sul',
    url: 'https://www.cetran.rs.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },

  // ==========================================
  // DISTRITO FEDERAL & CENTRO-OESTE (DF, GO, MT, MS)
  // ==========================================
  {
    id: 'SRC_DETRAN_DF',
    uf: 'DF',
    organId: 'DETRAN_DF',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-DF - Portal de Serviços e Defesa Prévia / JARI',
    url: 'https://www.detran.df.gov.br/infracoes/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CONTRANDIFE_DF',
    uf: 'DF',
    organId: 'CONTRANDIFE_DF',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CONTRANDIFE - Conselho de Trânsito do Distrito Federal',
    url: 'https://www.contrandife.df.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_GO',
    uf: 'GO',
    organId: 'DETRAN_GO',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-GO - Portal de Recursos e JARI Goiás',
    url: 'https://www.detran.go.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_GO',
    uf: 'GO',
    organId: 'CETRAN_GO',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-GO - Conselho Estadual de Trânsito de Goiás',
    url: 'https://www.cetran.go.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_MT',
    uf: 'MT',
    organId: 'DETRAN_MT',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-MT - Portal Oficial de Multas e Recursos',
    url: 'https://www.detran.mt.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_MT',
    uf: 'MT',
    organId: 'CETRAN_MT',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-MT - Conselho Estadual de Trânsito de Mato Grosso',
    url: 'https://www.cetran.mt.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_MS',
    uf: 'MS',
    organId: 'DETRAN_MS',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-MS - Portal de Multas e Notificações de MS',
    url: 'https://www.detran.ms.gov.br/infracoes/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_MS',
    uf: 'MS',
    organId: 'CETRAN_MS',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-MS - Conselho Estadual de Trânsito de Mato Grosso do Sul',
    url: 'https://www.cetran.ms.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },

  // ==========================================
  // NORDESTE (BA, PE, CE, MA, PB, RN, AL, SE, PI)
  // ==========================================
  {
    id: 'SRC_DETRAN_BA',
    uf: 'BA',
    organId: 'DETRAN_BA',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-BA - Portal de Defesa de Autuação e Recursos JARI',
    url: 'https://www.detran.ba.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_BA',
    uf: 'BA',
    organId: 'CETRAN_BA',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-BA - Conselho Estadual de Trânsito da Bahia',
    url: 'https://www.cetran.ba.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_PE',
    uf: 'PE',
    organId: 'DETRAN_PE',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-PE - Central de Defesas e Recursos Administrativos',
    url: 'https://www.detran.pe.gov.br/infracoes/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_PE',
    uf: 'PE',
    organId: 'CETRAN_PE',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-PE - Conselho Estadual de Trânsito de Pernambuco',
    url: 'https://www.cetran.pe.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_CE',
    uf: 'CE',
    organId: 'DETRAN_CE',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-CE - Protocolo de Recursos de Multas',
    url: 'https://www.detran.ce.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_CE',
    uf: 'CE',
    organId: 'CETRAN_CE',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-CE - Conselho Estadual de Trânsito do Ceará',
    url: 'https://www.cetran.ce.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_MA',
    uf: 'MA',
    organId: 'DETRAN_MA',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-MA - Portal de Serviços e Defesa de Notificações',
    url: 'https://www.detran.ma.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_MA',
    uf: 'MA',
    organId: 'CETRAN_MA',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-MA - Conselho Estadual de Trânsito do Maranhão',
    url: 'https://www.cetran.ma.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_PB',
    uf: 'PB',
    organId: 'DETRAN_PB',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-PB - Defesas e Recursos de Multas',
    url: 'https://detran.pb.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_PB',
    uf: 'PB',
    organId: 'CETRAN_PB',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-PB - Conselho Estadual de Trânsito da Paraíba',
    url: 'https://cetran.pb.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_RN',
    uf: 'RN',
    organId: 'DETRAN_RN',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-RN - Protocolo e Junta de Recursos JARI',
    url: 'https://www.detran.rn.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_RN',
    uf: 'RN',
    organId: 'CETRAN_RN',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-RN - Conselho Estadual de Trânsito do Rio Grande do Norte',
    url: 'https://www.cetran.rn.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_AL',
    uf: 'AL',
    organId: 'DETRAN_AL',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-AL - Portal de Recursos de Infrações',
    url: 'https://www.detran.al.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_AL',
    uf: 'AL',
    organId: 'CETRAN_AL',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-AL - Conselho Estadual de Trânsito de Alagoas',
    url: 'https://cetran.al.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_SE',
    uf: 'SE',
    organId: 'DETRAN_SE',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-SE - Defesa Prévia e Recursos JARI Sergipe',
    url: 'https://www.detran.se.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_SE',
    uf: 'SE',
    organId: 'CETRAN_SE',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-SE - Conselho Estadual de Trânsito de Sergipe',
    url: 'https://cetran.se.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_PI',
    uf: 'PI',
    organId: 'DETRAN_PI',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-PI - Recursos de Multas Piauí',
    url: 'https://www.detran.pi.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_PI',
    uf: 'PI',
    organId: 'CETRAN_PI',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-PI - Conselho Estadual de Trânsito do Piauí',
    url: 'https://cetran.pi.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },

  // ==========================================
  // NORTE (AM, PA, RO, TO, AC, AP, RR)
  // ==========================================
  {
    id: 'SRC_DETRAN_AM',
    uf: 'AM',
    organId: 'DETRAN_AM',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-AM - Portal de Recursos e Infrações Amazonas',
    url: 'https://www.detran.am.gov.br/servicos/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_AM',
    uf: 'AM',
    organId: 'CETRAN_AM',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-AM - Conselho Estadual de Trânsito do Amazonas',
    url: 'https://www.cetran.am.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_PA',
    uf: 'PA',
    organId: 'DETRAN_PA',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-PA - Central de Recursos e Multas Pará',
    url: 'https://www.detran.pa.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_PA',
    uf: 'PA',
    organId: 'CETRAN_PA',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-PA - Conselho Estadual de Trânsito do Pará',
    url: 'https://www.cetran.pa.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_RO',
    uf: 'RO',
    organId: 'DETRAN_RO',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-RO - Portal de Infrações e JARI Rondônia',
    url: 'https://www.detran.ro.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_RO',
    uf: 'RO',
    organId: 'CETRAN_RO',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-RO - Conselho Estadual de Trânsito de Rondônia',
    url: 'https://www.cetran.ro.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_TO',
    uf: 'TO',
    organId: 'DETRAN_TO',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-TO - Defesa Prévia e Recursos Tocantins',
    url: 'https://www.detran.to.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_TO',
    uf: 'TO',
    organId: 'CETRAN_TO',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-TO - Conselho Estadual de Trânsito do Tocantins',
    url: 'https://www.cetran.to.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_AC',
    uf: 'AC',
    organId: 'DETRAN_AC',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-AC - Portal de Serviços e Defesa de Multas Acre',
    url: 'https://www.detran.ac.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_AC',
    uf: 'AC',
    organId: 'CETRAN_AC',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-AC - Conselho Estadual de Trânsito do Acre',
    url: 'https://www.cetran.ac.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_AP',
    uf: 'AP',
    organId: 'DETRAN_AP',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-AP - Portal de Recursos Amapá',
    url: 'https://www.detran.ap.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_AP',
    uf: 'AP',
    organId: 'CETRAN_AP',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-AP - Conselho Estadual de Trânsito do Amapá',
    url: 'https://www.cetran.ap.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_DETRAN_RR',
    uf: 'RR',
    organId: 'DETRAN_RR',
    tier: 'TIER_1_GOV_PRIMARY',
    title: 'DETRAN-RR - Recursos de Multas Roraima',
    url: 'https://www.detran.rr.gov.br/recursos',
    category: 'portal_recurso',
    isActive: true,
  },
  {
    id: 'SRC_CETRAN_RR',
    uf: 'RR',
    organId: 'CETRAN_RR',
    tier: 'TIER_3_JUDICIAL_TRIBUNAL',
    title: 'CETRAN-RR - Conselho Estadual de Trânsito de Roraima',
    url: 'https://www.cetran.rr.gov.br',
    category: 'portal_recurso',
    isActive: true,
  },
];
