-- Ensure public.cases table exists (was never committed as a CREATE migration).
CREATE TABLE IF NOT EXISTS public.cases (
    id                          uuid PRIMARY KEY,
    app_ref                     text UNIQUE,
    title                       text NOT NULL,
    client_name                 text NOT NULL,
    client_email                text,
    client_phone                text,
    client_cpf                  text,
    user_id                     uuid,
    status                      text NOT NULL DEFAULT 'novo',
    current_stage               integer NOT NULL DEFAULT 0,
    service_type                text NOT NULL,
    vehicle_plate               text,
    vehicle_brand_model         text,
    vehicle_color               text,
    vehicle_chassis             text,
    vehicle_renavam             text,
    vehicle_year                text,
    infraction_code             text,
    infraction_description      text,
    ait_number                  text,
    autuador_body               text,
    fine_amount                 numeric NOT NULL DEFAULT 0,
    points                      integer NOT NULL DEFAULT 0,
    severity                    text NOT NULL DEFAULT 'media',
    speed_limit                 numeric,
    considered_speed            numeric,
    measured_speed              numeric,
    date_time                   timestamptz,
    location                    text,
    radar_equipment_id          text,
    inmetro_aferition_date      timestamptz,
    notification_expedition_date timestamptz,
    defense_deadline            timestamptz,
    formal_flaws_json           jsonb NOT NULL DEFAULT '[]'::jsonb,
    analysis_json               jsonb,
    defense_draft_json          jsonb,
    ocr_auxiliary_json          jsonb,
    protocol_info_json          jsonb,
    timeline_json               jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence_json               jsonb,
    ctb_article                 text,
    is_anonymous                boolean NOT NULL DEFAULT true,
    claim_token                 text,
    is_paid                     boolean NOT NULL DEFAULT false,
    paid_at                     timestamptz,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cases_claim_token ON public.cases(claim_token) WHERE claim_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cases_user_id ON public.cases(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cases_claim_token_user_id ON public.cases(claim_token, user_id) WHERE claim_token IS NOT NULL AND user_id IS NULL;
