-- ============================================================================
-- FASE 9 — RECONCILIAÇÃO DETERMINÍSTICA DO ACERVO (artefato de reprodutibilidade)
-- Data: 2026-09-24 | Fase 10 (Gap 1)
-- Reproduz deterministicamente a carga: Inventário Fase 8 -> 39 sources /
-- 66 documents / 66 versions, com lineage, hashes e metadata.
--
-- Idempotente: ON CONFLICT (id) DO NOTHING. Nenhum DROP/DELETE/TRUNCATE.
-- Segurança: não cria policies; preserva RLS (default service-role).
--
-- DEPENDÊNCIA FORMAL: IDs canônicos (SRC_*) e content_hash provêm do
-- inventário Fase 8 (FASE-8-INVENTARIO-DOCUMENTAL-OFICIAL-2026-09-23.md) e dos
-- arquivos físicos de legal_collected_2026_09_23/. Reprodução 100% independente
-- exige esses dois insumos (documentado na Fase 10).
-- Executar com role administrativo (service_role / supabase_admin). Testar em
-- banco de prova antes do canônico.
-- ============================================================================

-- sources
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_PLANALTO','Planalto','LAW','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_SENATRAN','SENATRAN','GOVERNMENT','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_CONTRAN','CONTRAN','REGULATION','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_PRF','PRF','GOVERNMENT','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_DNIT','DNIT','GOVERNMENT','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_ANTT','ANTT','GOVERNMENT','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_INMETRO','INMETRO','GOVERNMENT','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_DOU','DOU','GOVERNMENT','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_FED_STJ','STJ','JURISPRUDENCE','Federal','BR_FEDERAL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_AC_DETRAN_AC','DETRAN-AC','REGULATION','Estadual','AC',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_AP_DETRAN_AP','DETRAN-AP','GOVERNMENT','DETRAN-AP','AP',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_AL_CETRAN_AL','CETRAN-AL','REGULATION','Estadual','AL',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_AM_DETRAN_AM','DETRAN-AM','REGULATION','Estadual','AM',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_CE_DETRAN_CE','DETRAN-CE','GOVERNMENT','Estadual','CE',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_CE_CETRAN_CE','CETRAN-CE','REGULATION','CETRAN-CE','CE',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_ES_DETRAN_ES','DETRAN-ES','GOVERNMENT','Estadual','ES',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_ES_CETRAN_ES','CETRAN-ES','REGULATION','Estadual','ES',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_GO_DETRAN_GO','DETRAN-GO','GOVERNMENT','DETRAN-GO','GO',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_GO_CETRAN_GO','CETRAN-GO','REGULATION','CETRAN-GO','GO',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_MG_DETRAN_MG','DETRAN-MG','GOVERNMENT','DETRAN-MG','MG',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_MS_DETRAN_MS','DETRAN-MS','REGULATION','DETRAN-MS','MS',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_MS_CETRAN_MS','CETRAN-MS','REGULATION','CETRAN-MS','MS',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_PA_DETRAN_PA','DETRAN-PA','GOVERNMENT','DETRAN-PA','PA',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_PB_DETRAN_PB','DETRAN-PB','GOVERNMENT','DETRAN-PB','PB',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_PB_CETRAN_PB','CETRAN-PB','REGULATION','CETRAN-PB','PB',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_PI_DETRAN_PI','DETRAN-PI','GOVERNMENT','DETRAN-PI','PI',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_PI_CETRAN_PI','CETRAN-PI','REGULATION','CETRAN-PI','PI',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_PR_DETRAN_PR','DETRAN-PR','GOVERNMENT','DETRAN-PR','PR',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_PR_CETRAN_PR','CETRAN-PR','LAW','CETRAN-PR','PR',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_RJ_DETRAN_RJ','DETRAN-RJ','GOVERNMENT','DETRAN-RJ','RJ',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_RJ_CETRAN_RJ','CETRAN-RJ','LAW','CETRAN-RJ','RJ',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_RR_DETRAN_RR','DETRAN-RR','GOVERNMENT','DETRAN-RR','RR',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_RS_DETRAN_RS','DETRAN-RS','GOVERNMENT','DETRAN-RS','RS',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_RS_CETRAN_RS','CETRAN-RS','LAW','CETRAN-RS','RS',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_SC_DETRAN_SC','DETRAN-SC','GOVERNMENT','DETRAN-SC','SC',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_SC_CETRAN_SC','CETRAN-SC','LAW','CETRAN-SC','SC',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_SP_DETRAN_SP','DETRAN-SP','GOVERNMENT','DETRAN-SP','SP',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_SP_CETRAN_SP','CETRAN-SP','LAW','CETRAN-SP','SP',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;
insert into knowledge_sources (id,name,source_type,authority,jurisdiction,url,is_active,created_at,updated_at,description) values ('SRC_TO_DETRAN_TO','DETRAN-TO','GOVERNMENT','DETRAN-TO','TO',null,true,now(),now(),'Fonte identificada na Fase 8 (acervo) - reconcile 2026-09-24') on conflict (id) do nothing;

insert into knowledge_documents (id,source_id,title,document_type,jurisdiction,status,metadata) values
('SRC_FED_PLANALTO_CTB','SRC_FED_PLANALTO','Compilação do CTB','Código de Trânsito Brasileiro (Lei 9.503/1997)','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_PLANALTO_CTB","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T18:16:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm"}'),
('SRC_FED_SENATRAN_PORTAL','SRC_FED_SENATRAN','Página inicial da SENATRAN','Portal da SENATRAN','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_SENATRAN_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:10:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/transportes/pt-br/assuntos/transito/senatran"}'),
('SRC_FED_CONTRAN_RESOLUCOES','SRC_FED_CONTRAN','Compilação de Resoluções do CONTRAN','Resoluções do CONTRAN','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_CONTRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:17:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/transportes/pt-br/assuntos/transito/senatran/contran"}'),
('SRC_FED_CONTRAN_796_2020_RECUPERADO','SRC_FED_CONTRAN','Resolução CONTRAN 796/2020 (cópia recuperada)','Resolução CONTRAN 796/2020','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_CONTRAN_796_2020_RECUPERADO","collection_state":"RECUPERADO","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T20:39:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/transportes/pt-br/assuntos/transito/conteudo-contran/resolucoes/Resolucao7962020.pdf","recovered":true}'),
('SRC_FED_PRF_PORTAL','SRC_FED_PRF','Página inicial do portal de multas da PRF','Portal de Multas e Defesas da PRF','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_PRF_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:11:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://sistemas.prf.gov.br/portal/recursos"}'),
('SRC_FED_DNIT_PORTAL','SRC_FED_DNIT','Página inicial do portal de multas do DNIT','Portal de Multas e Defesas do DNIT','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_DNIT_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T18:18:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://servicos.dnit.gov.br/multas"}'),
('SRC_FED_ANTT_PORTAL','SRC_FED_ANTT','Página inicial do portal de multas da ANTT','Portal de Multas e Defesas da ANTT','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_ANTT_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:12:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/antt/pt-br/assuntos/passageiros/fiscalizacao-e-multas"}'),
('SRC_FED_INMETRO_RADARES','SRC_FED_INMETRO','Sistema de consulta de radares cronotacógrafos','Consulta de Radares e Cronotacógrafos','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_INMETRO_RADARES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:13:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://cronotacografo.rbmlq.gov.br/certificados/consultar"}'),
('SRC_FED_DOU','SRC_FED_DOU','Consulta ao Diário Oficial da União','Diário Oficial da União','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_DOU","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:14:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.in.gov.br/leiturajornal"}'),
('SRC_FED_STJ_JURISPRUDENCIA','SRC_FED_STJ','Portal de jurisprudência do STJ em teses','Jurisprudência em Teses - STJ','BR_FEDERAL','ACTIVE','{"fase8_inventory_id":"SRC_FED_STJ_JURISPRUDENCIA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:15:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://scon.stj.jus.br/SCON/"}'),
('SRC_AC_DETRAN_PORTARIA_NOVA_PROCURAA','SRC_AC_DETRAN_AC','Nova Portaria PROCURAA_A_O','Portaria','AC','ACTIVE','{"fase8_inventory_id":"SRC_AC_DETRAN_PORTARIA_NOVA_PROCURAA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T22:42:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ac.gov.br/wp-content/uploads/2025/12/nova-portaria-PROCURAA_A_O.pdf"}'),
('SRC_AC_DETRAN_PORTARIA_1159_2024','SRC_AC_DETRAN_AC','Portaria n° 1159/2024 - Alteração de Portaria (assinatura digital)','Portaria','AC','ACTIVE','{"fase8_inventory_id":"SRC_AC_DETRAN_PORTARIA_1159_2024","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T22:43:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ac.gov.br/wp-content/uploads/2025/03/Portaria_n__1159_2024_alteracao_portaria_assinatura_digital.pdf"}')
on conflict (id) do nothing;
insert into knowledge_documents (id,source_id,title,document_type,jurisdiction,status,metadata) values
('SRC_AC_DETRAN_PORTARIA_1723','SRC_AC_DETRAN_AC','Portaria 1723','Portaria','AC','ACTIVE','{"fase8_inventory_id":"SRC_AC_DETRAN_PORTARIA_1723","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T22:44:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ac.gov.br/wp-content/uploads/2024/04/Portaria_1723.pdf"}'),
('SRC_AP_DETRAN_REQUERIMENTO_INFRACAO','SRC_AP_DETRAN_AP','Requerimento de Infração','Formulário','AP','ACTIVE','{"fase8_inventory_id":"SRC_AP_DETRAN_REQUERIMENTO_INFRACAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T22:34:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ap.gov.br/detranap/wp-content/uploads/2026/04/requerimento-infracao.pdf"}'),
('SRC_AP_DETRAN_SOLICITACAO_SERVICOS','SRC_AP_DETRAN_AP','Solicitação de Serviços','Formulário','AP','ACTIVE','{"fase8_inventory_id":"SRC_AP_DETRAN_SOLICITACAO_SERVICOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T22:34:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ap.gov.br/detranap/wp-content/uploads/2026/04/solicitacao-de-servicos.pdf"}'),
('SRC_AL_CETRAN_RESOLUCAO_01_2000','SRC_AL_CETRAN_AL','RESOLUÇÃO CETRAN Nº 01/2000','Resolução','AL','ACTIVE','{"fase8_inventory_id":"SRC_AL_CETRAN_RESOLUCAO_01_2000","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:00:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=68&catid=87&m=0"}'),
('SRC_AL_CETRAN_RESOLUCAO_04_2002','SRC_AL_CETRAN_AL','RESOLUÇÃO CETRAN Nº 04/2002','Resolução','AL','ACTIVE','{"fase8_inventory_id":"SRC_AL_CETRAN_RESOLUCAO_04_2002","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:01:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=71&catid=87&m=0"}'),
('SRC_AL_CETRAN_RESOLUCAO_02_2000','SRC_AL_CETRAN_AL','RESOLUÇÃO CETRAN Nº 02/2000','Resolução','AL','ACTIVE','{"fase8_inventory_id":"SRC_AL_CETRAN_RESOLUCAO_02_2000","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:02:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=69&catid=87&m=0"}'),
('SRC_AM_DETRAN_PORTARIA_NORMATIVA_015_2026','SRC_AM_DETRAN_AM','PORTARIA NORMATIVA No. 015/2026','Portaria','AM','ACTIVE','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_NORMATIVA_015_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:30:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/07/PORTARIA-NORMATIVA-No-015.pdf"}'),
('SRC_AM_DETRAN_PORTARIA_NORMATIVA_014_2026','SRC_AM_DETRAN_AM','PORTARIA NORMATIVA No. 014/2026','Portaria','AM','ACTIVE','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_NORMATIVA_014_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:31:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/07/PORTARIA-NORMATIVA-No-014.pdf"}'),
('SRC_AM_MEMO_753_2026_RECUPERADO','SRC_AM_DETRAN_AM','MEMO N° 753/2026 - OPTRAN DETRAN (cópia recuperada)','Memo','AM','ACTIVE','{"fase8_inventory_id":"SRC_AM_MEMO_753_2026_RECUPERADO","collection_state":"RECUPERADO","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T20:39:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/09/MEMO_N_753_2026_OPTRAN_DETRAN_Portaria.pdf","recovered":true}'),
('SRC_AM_DETRAN_PORTARIA_01_03_011210_078105_2026_96','SRC_AM_DETRAN_AM','Portaria 01.03.011210.078105/2026-96','Portaria','AM','ACTIVE','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_01_03_011210_078105_2026_96","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:33:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/08/01.03.011210.078105_2026_96_Portaria.pdf"}'),
('SRC_AM_DETRAN_PORTARIA_01_03_011210_083647_2026_80','SRC_AM_DETRAN_AM','Portaria 01.03.011210.083647/2026-80','Portaria','AM','ACTIVE','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_01_03_011210_083647_2026_80","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:34:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/08/01.03.011210.083647_2026_80_Portaria.pdf"}'),
('SRC_CE_DETRAN_INSTRUCAO_SERVICO_004_2007_COHAB','SRC_CE_DETRAN_CE','Instrução de Serviços nº 004/2007 – COHAB','Instrução de Serviço','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_DETRAN_INSTRUCAO_SERVICO_004_2007_COHAB","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/wp-content/uploads/sites/91/2010/06/is004_2007_cohab.pdf"}')
on conflict (id) do nothing;
insert into knowledge_documents (id,source_id,title,document_type,jurisdiction,status,metadata) values
('SRC_CE_DETRAN_DEFESA_AUTUAR_INFRACAO','SRC_CE_DETRAN_CE','Defesa de autuação de infração de trânsito','Serviço','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_DETRAN_DEFESA_AUTUAR_INFRACAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/"}'),
('SRC_CE_DETRAN_RECURSO_JARI','SRC_CE_DETRAN_CE','Recurso JARI - DETRAN-CE','Serviço','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_DETRAN_RECURSO_JARI","collection_state":"DUPLICATA_EXATA","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","duplicate_of":"SRC_CE_DETRAN_DEFESA_AUTUAR_INFRACAO"}'),
('SRC_CE_CETRAN_REGIMENTO_INTERNO_2020','SRC_CE_CETRAN_CE','Regimento Interno CETRAN-CE 2020','Regimento Interno','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_CETRAN_REGIMENTO_INTERNO_2020","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/"}'),
('SRC_CE_CETRAN_RESOLUCAO_001_2013','SRC_CE_CETRAN_CE','Resolução CETRAN-CE 001/2013','Resolução','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_001_2013","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/"}'),
('SRC_CE_CETRAN_RESOLUCAO_001_2014','SRC_CE_CETRAN_CE','Resolução CETRAN-CE 001/2014','Resolução','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_001_2014","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/"}'),
('SRC_CE_CETRAN_RESOLUCAO_003_2019','SRC_CE_CETRAN_CE','Resolução CETRAN-CE 003/2019','Resolução','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_003_2019","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/"}'),
('SRC_CE_CETRAN_RESOLUCAO_005','SRC_CE_CETRAN_CE','Resolução CETRAN-CE 005','Resolução','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_005","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/"}'),
('SRC_CE_CETRAN_RESOLUCAO_006','SRC_CE_CETRAN_CE','Resolução CETRAN-CE 006','Resolução','CE','ACTIVE','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_006","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/"}'),
('SRC_ES_DETRAN_RECURSO_MULTA_ONLINE','SRC_ES_DETRAN_ES','Recurso de Multa On-line','Procedimento','ES','ACTIVE','{"fase8_inventory_id":"SRC_ES_DETRAN_RECURSO_MULTA_ONLINE","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T01:37:56Z","content_state":"NOT_STORED_FASE9","origin_url":"https://detran.es.gov.br/recurso-de-multa-online"}'),
('SRC_ES_CETRAN_RESOLUCAO_20_2026','SRC_ES_CETRAN_ES','RESOLUÇÃO CETRAN Nº 20-2026','Resolução','ES','ACTIVE','{"fase8_inventory_id":"SRC_ES_CETRAN_RESOLUCAO_20_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T01:37:56Z","content_state":"NOT_STORED_FASE9","origin_url":"https://detran.es.gov.br/Media/detran/Legislacao/Resoluções/RESOLUÇÃO%20CETRAN%20Nº%2020-2026.pdf"}'),
('SRC_GO_DETRAN_DEFESA_PREVIA_PF','SRC_GO_DETRAN_GO','Requerimento de Defesa Prévia - Pessoa Física','Formulário','GO','ACTIVE','{"fase8_inventory_id":"SRC_GO_DETRAN_DEFESA_PREVIA_PF","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T02:50:55Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.go.gov.br/"}'),
('SRC_GO_CETRAN_RESOLUCAO_1999_003','SRC_GO_CETRAN_GO','RESOLUÇÃO CETRAN GO nº 1999/003','Resolução','GO','ACTIVE','{"fase8_inventory_id":"SRC_GO_CETRAN_RESOLUCAO_1999_003","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T02:51:31Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.go.gov.br/"}')
on conflict (id) do nothing;
insert into knowledge_documents (id,source_id,title,document_type,jurisdiction,status,metadata) values
('SRC_MG_DETRAN_DEFESA_PREVIA_PF','SRC_MG_DETRAN_MG','Apresentar defesa prévia (multa)','Serviço','MG','ACTIVE','{"fase8_inventory_id":"SRC_MG_DETRAN_DEFESA_PREVIA_PF","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T14:31:34Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.mg.gov.br/infracoes/multa/apresentar-defesa-previa-infracao-1"}'),
('SRC_MS_DETRAN_PORTARIA_211_2026','SRC_MS_DETRAN_MS','PORTARIA DETRAN/MS Nº 211 DE 18 DE JUNHO DE 2026','Portaria','MS','ACTIVE','{"fase8_inventory_id":"SRC_MS_DETRAN_PORTARIA_211_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:19:44Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ms.gov.br/wp-content/uploads/2026/06/PORTARIA-DETRANMS-N-No-211-DE-18-DE-JUNHO-DE-2026.pdf"}'),
('SRC_MS_CETRAN_REGIMENTO_INTERNO','SRC_MS_CETRAN_MS','Regimento Interno do CETRAN-MS','Regimento Interno','MS','ACTIVE','{"fase8_inventory_id":"SRC_MS_CETRAN_REGIMENTO_INTERNO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:19:46Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.sejusp.ms.gov.br/wp-content/uploads/2025/11/Regimento-Interno-CETRAN.pdf"}'),
('SRC_PA_DETRAN_PORTAL','SRC_PA_DETRAN_PA','Portal oficial do DETRAN-PA (shell SPA)','Portal','PA','ACTIVE','{"fase8_inventory_id":"SRC_PA_DETRAN_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:29:16Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.pa.gov.br/"}'),
('SRC_PB_DETRAN_DEFESA_RECURSOS_ONLINE','SRC_PB_DETRAN_PB','Defesa/Recursos Online','Serviço','PB','ACTIVE','{"fase8_inventory_id":"SRC_PB_DETRAN_DEFESA_RECURSOS_ONLINE","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:32:16Z","content_state":"NOT_STORED_FASE9","origin_url":"https://detran.pb.gov.br/infracoes/recursos-defesa-online"}'),
('SRC_PB_CETRAN_REGIMENTO_INTERNO','SRC_PB_CETRAN_PB','Regimento Interno CETRAN-PB','Regimento Interno','PB','ACTIVE','{"fase8_inventory_id":"SRC_PB_CETRAN_REGIMENTO_INTERNO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:32:20Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.pb.gov.br/legislacao/Regimento%20interno/@@download/file/Safari.pdf"}'),
('SRC_PI_DETRAN_MULTAS_ART320','SRC_PI_DETRAN_PI','Multas de Trânsito DETRAN-PI - ART. 320 do CTB','Informação Jurídica','PI','ACTIVE','{"fase8_inventory_id":"SRC_PI_DETRAN_MULTAS_ART320","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:36:21Z","content_state":"NOT_STORED_FASE9","origin_url":"https://portal.pi.gov.br/detran/multas-de-transito-detran-pi-art-320-do-ctb/"}'),
('SRC_PI_DETRAN_RECURSO_MULTA','SRC_PI_DETRAN_PI','Cadastro de Recurso de Multa (GETRAN)','Serviço','PI','ACTIVE','{"fase8_inventory_id":"SRC_PI_DETRAN_RECURSO_MULTA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:36:21Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.pi.getran.com.br/site/apps/multa/recurso/cadastrar-recurso.jsp"}'),
('SRC_PI_CETRAN_DECRETO_22731_2024','SRC_PI_CETRAN_PI','Decreto nº 22.731 de 02 de fevereiro de 2024','Decreto','PI','ACTIVE','{"fase8_inventory_id":"SRC_PI_CETRAN_DECRETO_22731_2024","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:37:24Z","content_state":"NOT_STORED_FASE9","origin_url":"https://portal.pi.gov.br/detran/wp-content/uploads/sites/62/2025/11/DECRETO-No-22.731-DE-02-DE-FEVEREIRO-DE-2024.pdf"}'),
('SRC_PI_CETRAN_DECRETO_24023_2025','SRC_PI_CETRAN_PI','Decreto nº 24.023 de 19 de agosto de 2025','Decreto','PI','ACTIVE','{"fase8_inventory_id":"SRC_PI_CETRAN_DECRETO_24023_2025","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:37:24Z","content_state":"NOT_STORED_FASE9","origin_url":"https://portal.pi.gov.br/detran/wp-content/uploads/sites/62/2025/11/DECRETO-No-24.023-DE-19-DE-AGOSTO-DE-2025.pdf"}'),
('SRC_PR_DETRAN_RECURSOS','SRC_PR_DETRAN_PR','Recursos - DETRAN/PR','Procedimento','PR','ACTIVE','{"fase8_inventory_id":"SRC_PR_DETRAN_RECURSOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:39:05Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.pr.gov.br/Pagina/Recursos"}'),
('SRC_PR_CETRAN_RESOLUCOES','SRC_PR_CETRAN_PR','Resoluções - CETRAN/PR','Legislação','PR','ACTIVE','{"fase8_inventory_id":"SRC_PR_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:39:05Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.pr.gov.br/Pagina/Resolucoes"}')
on conflict (id) do nothing;
insert into knowledge_documents (id,source_id,title,document_type,jurisdiction,status,metadata) values
('SRC_PR_CETRAN_RESOLUCAO_077_2021','SRC_PR_CETRAN_PR','Resolução 077/21 - regras e procedimentos para fiscalização de trânsito de ciclomotores, ciclomotores elétricos e equiparados','Resolução','PR','ACTIVE','{"fase8_inventory_id":"SRC_PR_CETRAN_RESOLUCAO_077_2021","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:39:05Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.pr.gov.br/sites/cetran/arquivos_restritos/files/documento/2021-11/resolucao_077_-21_regras_e_procedimentos_para_a_fiscalizacao_de_transito_dos_ciclomotores_cicloeletricos_e_equiparados.pdf"}'),
('SRC_RJ_DETRAN_FORMULARIOS_INFRACOES','SRC_RJ_DETRAN_RJ','Formulários de Infrações','Serviço','RJ','ACTIVE','{"fase8_inventory_id":"SRC_RJ_DETRAN_FORMULARIOS_INFRACOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:41:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rj.gov.br/formulario/formularios-de-infracoes"}'),
('SRC_RJ_DETRAN_FORMULARIO_DEFESA_RECURSO','SRC_RJ_DETRAN_RJ','CJC0160 - Apresentação de Defesa/Recurso','Formulário','RJ','ACTIVE','{"fase8_inventory_id":"SRC_RJ_DETRAN_FORMULARIO_DEFESA_RECURSO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:41:01Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rj.gov.br/images/ascom/pdf/formularios/CJC0160_apresentacao_defesa_recurso.pdf"}'),
('SRC_RJ_CETRAN_RESOLUCOES','SRC_RJ_CETRAN_RJ','Resoluções CETRAN-RJ','Legislação','RJ','ACTIVE','{"fase8_inventory_id":"SRC_RJ_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:41:00Z","content_state":"NOT_STORED_FASE9","origin_url":"http://www.cetran.rj.gov.br/estadual/resolucoes-cetran"}'),
('SRC_RR_DETRAN_DEFESA_PREVIA','SRC_RR_DETRAN_RR','Multas em fase de Autuação – Defesa Prévia','Serviço','RR','ACTIVE','{"fase8_inventory_id":"SRC_RR_DETRAN_DEFESA_PREVIA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:47:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rr.gov.br/infracoes/informacoes/multas-em-fase-de-autuacao-defesa-previa/"}'),
('SRC_RR_DETRAN_RECURSO_AUTUACAO_DEFESA','SRC_RR_DETRAN_RR','Recurso de Autuação - Defesa Prévia','Formulário','RR','ACTIVE','{"fase8_inventory_id":"SRC_RR_DETRAN_RECURSO_AUTUACAO_DEFESA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:47:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rr.gov.br/wp-content/uploads/2022/07/recurso_de_autuacao_-_defesa_previa.pdf"}'),
('SRC_RR_DETRAN_RECURSO_CETRAN','SRC_RR_DETRAN_RR','Recurso ao CETRAN-RR','Formulário','RR','ACTIVE','{"fase8_inventory_id":"SRC_RR_DETRAN_RECURSO_CETRAN","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:47:51Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rr.gov.br/wp-content/uploads/2022/07/recurso_ao_CETRAN_-_RR.pdf"}'),
('SRC_RS_DETRAN_APRESENTAR_DEFESA_RECURSO','SRC_RS_DETRAN_RS','Apresentar defesa e recurso','Serviço','RS','ACTIVE','{"fase8_inventory_id":"SRC_RS_DETRAN_APRESENTAR_DEFESA_RECURSO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:50:39Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rs.gov.br/apresentar-defesa-e-recurso"}'),
('SRC_RS_CETRAN_RESOLUCOES','SRC_RS_CETRAN_RS','Resoluções - CETRAN/RS','Legislação','RS','ACTIVE','{"fase8_inventory_id":"SRC_RS_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:50:39Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.rs.gov.br/resolucoes"}'),
('SRC_SC_DETRAN_MULTAS_PENALIDADES','SRC_SC_DETRAN_SC','Multas e Penalidades','Serviço','SC','ACTIVE','{"fase8_inventory_id":"SRC_SC_DETRAN_MULTAS_PENALIDADES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:52:59Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.sc.gov.br/multas-e-penalidades/"}'),
('SRC_SC_DETRAN_DEFESA_AUTUACAO','SRC_SC_DETRAN_SC','Defesa de Autuação','Serviço','SC','ACTIVE','{"fase8_inventory_id":"SRC_SC_DETRAN_DEFESA_AUTUACAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:52:59Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.sc.gov.br/defesa-de-autuacao/"}'),
('SRC_SC_CETRAN_RESOLUCOES','SRC_SC_CETRAN_SC','Resoluções - CETRAN/SC','Legislação','SC','ACTIVE','{"fase8_inventory_id":"SRC_SC_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:52:59Z","content_state":"NOT_STORED_FASE9","origin_url":"https://cetran.sc.gov.br/resolucoes/"}')
on conflict (id) do nothing;
insert into knowledge_documents (id,source_id,title,document_type,jurisdiction,status,metadata) values
('SRC_SP_DETRAN_PORTAL_DETRANSP','SRC_SP_DETRAN_SP','Portal Detran-SP (DetranSP)','Portal','SP','ACTIVE','{"fase8_inventory_id":"SRC_SP_DETRAN_PORTAL_DETRANSP","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:58:53Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.sp.gov.br/detransp"}'),
('SRC_SP_CETRAN_LEGISLACOES','SRC_SP_CETRAN_SP','Legislações - CETRAN/SP','Legislação','SP','ACTIVE','{"fase8_inventory_id":"SRC_SP_CETRAN_LEGISLACOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:58:53Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.sp.gov.br/CetranWeb/institucional/legislacoes"}'),
('SRC_SP_CETRAN_ATOS_NORMATIVOS','SRC_SP_CETRAN_SP','Atos Normativos - CETRAN/SP','Legislação','SP','ACTIVE','{"fase8_inventory_id":"SRC_SP_CETRAN_ATOS_NORMATIVOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:58:53Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.sp.gov.br/CetranWeb/atosnormativos"}'),
('SRC_TO_DETRAN_PORTAL','SRC_TO_DETRAN_TO','Portal DETRAN-TO','Portal','TO','ACTIVE','{"fase8_inventory_id":"SRC_TO_DETRAN_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T16:01:07Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.to.gov.br/detran/"}'),
('SRC_TO_DETRAN_FORMULARIO_RECURSOS','SRC_TO_DETRAN_TO','Formulário de Recursos','Serviço','TO','ACTIVE','{"fase8_inventory_id":"SRC_TO_DETRAN_FORMULARIO_RECURSOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T16:01:07Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.to.gov.br/detran/formulario-de-recursos/252b8affcn93"}'),
('SRC_TO_DETRAN_RECURSO_MULTAS_CIDADAO','SRC_TO_DETRAN_TO','Recurso de Multas - Portal Cidadão','Serviço','TO','ACTIVE','{"fase8_inventory_id":"SRC_TO_DETRAN_RECURSO_MULTAS_CIDADAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T16:01:07Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.to.gov.br/detran/recurso-de-multas-portal-cidadao/77a9q0bazri"}')
on conflict (id) do nothing;
insert into knowledge_document_versions (id,document_id,version,content_hash,content,source_url,metadata) values
('SRC_FED_PLANALTO_CTB_v1','SRC_FED_PLANALTO_CTB','v1.0','6a5e7d4ce6bd582acb0244b4b8a75837bb4cabc634842bbee2c99a58194e7d2e','','https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm','{"fase8_inventory_id":"SRC_FED_PLANALTO_CTB","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T18:16:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm","version_rank":1}'),
('SRC_FED_SENATRAN_PORTAL_v1','SRC_FED_SENATRAN_PORTAL','v1.0','3ec76f081ecd9ba75599ca8106be16c1039c15df7b11d6a3b8d74bc9265a1c4d','','https://www.gov.br/transportes/pt-br/assuntos/transito/senatran','{"fase8_inventory_id":"SRC_FED_SENATRAN_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:10:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/transportes/pt-br/assuntos/transito/senatran","version_rank":1}'),
('SRC_FED_CONTRAN_RESOLUCOES_v1','SRC_FED_CONTRAN_RESOLUCOES','v1.0','abbbe54018dde4f96fa27d3402e42f95e0ea93d754452ec7809f62a8249c13f0','','https://www.gov.br/transportes/pt-br/assuntos/transito/senatran/contran','{"fase8_inventory_id":"SRC_FED_CONTRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:17:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/transportes/pt-br/assuntos/transito/senatran/contran","version_rank":1}'),
('SRC_FED_CONTRAN_796_2020_RECUPERADO_v1','SRC_FED_CONTRAN_796_2020_RECUPERADO','v1.0','5bc7bade164377fce6abe301b8ae59a7de7a008598c3011a7fe6cb177fdd0c1d','','https://www.gov.br/transportes/pt-br/assuntos/transito/conteudo-contran/resolucoes/Resolucao7962020.pdf','{"fase8_inventory_id":"SRC_FED_CONTRAN_796_2020_RECUPERADO","collection_state":"RECUPERADO","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T20:39:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/transportes/pt-br/assuntos/transito/conteudo-contran/resolucoes/Resolucao7962020.pdf","recovered":true,"version_rank":1}'),
('SRC_FED_PRF_PORTAL_v1','SRC_FED_PRF_PORTAL','v1.0','6d4ab6b742457c58ad4c8f3c2d5ddad2643d4e9f32ead6bba69aa67b61fd102d','','https://sistemas.prf.gov.br/portal/recursos','{"fase8_inventory_id":"SRC_FED_PRF_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:11:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://sistemas.prf.gov.br/portal/recursos","version_rank":1}'),
('SRC_FED_DNIT_PORTAL_v1','SRC_FED_DNIT_PORTAL','v1.0','67debf6e429639a2e6f504e5f78434ca68b3e34961a971d6bcd9cdafb612ad7a','','https://servicos.dnit.gov.br/multas','{"fase8_inventory_id":"SRC_FED_DNIT_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T18:18:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://servicos.dnit.gov.br/multas","version_rank":1}'),
('SRC_FED_ANTT_PORTAL_v1','SRC_FED_ANTT_PORTAL','v1.0','a7c1d5a923af59c401aab4b95e89f94ac3f10e4ce9bbe556f63c72510790efd5','','https://www.gov.br/antt/pt-br/assuntos/passageiros/fiscalizacao-e-multas','{"fase8_inventory_id":"SRC_FED_ANTT_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:12:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.gov.br/antt/pt-br/assuntos/passageiros/fiscalizacao-e-multas","version_rank":1}'),
('SRC_FED_INMETRO_RADARES_v1','SRC_FED_INMETRO_RADARES','v1.0','e67d72bfcf159b1a79cbd89560fca53fa85e8748c84c3e671da998cf3b62e239','','https://cronotacografo.rbmlq.gov.br/certificados/consultar','{"fase8_inventory_id":"SRC_FED_INMETRO_RADARES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:13:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://cronotacografo.rbmlq.gov.br/certificados/consultar","version_rank":1}'),
('SRC_FED_DOU_v1','SRC_FED_DOU','v1.0','31d48bd3a918942e8233cfcd40cbac5cfc8807ecfa837060752af2eb0021f13a','','https://www.in.gov.br/leiturajornal','{"fase8_inventory_id":"SRC_FED_DOU","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:14:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.in.gov.br/leiturajornal","version_rank":1}'),
('SRC_FED_STJ_JURISPRUDENCIA_v1','SRC_FED_STJ_JURISPRUDENCIA','v1.0','caea3a0b1ab3a8dd6d41d9c185f1ea5dcccb3cccbc116926b166b297286a73fb','','https://scon.stj.jus.br/SCON/','{"fase8_inventory_id":"SRC_FED_STJ_JURISPRUDENCIA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-23T19:15:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://scon.stj.jus.br/SCON/","version_rank":1}'),
('SRC_AC_DETRAN_PORTARIA_NOVA_PROCURAA_v1','SRC_AC_DETRAN_PORTARIA_NOVA_PROCURAA','v1.0','11ef1de1afb04c0100e1162b0b07ed052c7228e1029a5e66b9a6f1c6c52441ce','','https://www.detran.ac.gov.br/wp-content/uploads/2025/12/nova-portaria-PROCURAA_A_O.pdf','{"fase8_inventory_id":"SRC_AC_DETRAN_PORTARIA_NOVA_PROCURAA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T22:42:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ac.gov.br/wp-content/uploads/2025/12/nova-portaria-PROCURAA_A_O.pdf","version_rank":1}'),
('SRC_AC_DETRAN_PORTARIA_1159_2024_v1','SRC_AC_DETRAN_PORTARIA_1159_2024','v1.0','991e9fcb9edd07550298b4f81a88de13282263968da47f800244e587bf7b438c','','https://www.detran.ac.gov.br/wp-content/uploads/2025/03/Portaria_n__1159_2024_alteracao_portaria_assinatura_digital.pdf','{"fase8_inventory_id":"SRC_AC_DETRAN_PORTARIA_1159_2024","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T22:43:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ac.gov.br/wp-content/uploads/2025/03/Portaria_n__1159_2024_alteracao_portaria_assinatura_digital.pdf","version_rank":1}')
on conflict (id) do nothing;
insert into knowledge_document_versions (id,document_id,version,content_hash,content,source_url,metadata) values
('SRC_AC_DETRAN_PORTARIA_1723_v1','SRC_AC_DETRAN_PORTARIA_1723','v1.0','175e22e4daa442ff3115804f7319e8a3c3979be1847252d32a972788f6a2794d','','https://www.detran.ac.gov.br/wp-content/uploads/2024/04/Portaria_1723.pdf','{"fase8_inventory_id":"SRC_AC_DETRAN_PORTARIA_1723","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T22:44:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ac.gov.br/wp-content/uploads/2024/04/Portaria_1723.pdf","version_rank":1}'),
('SRC_AP_DETRAN_REQUERIMENTO_INFRACAO_v1','SRC_AP_DETRAN_REQUERIMENTO_INFRACAO','v1.0','7a2e6e7383a31724eedd7e2d498714cafcf50071b9cdb61d46f5c49e0e5ca953','','https://www.detran.ap.gov.br/detranap/wp-content/uploads/2026/04/requerimento-infracao.pdf','{"fase8_inventory_id":"SRC_AP_DETRAN_REQUERIMENTO_INFRACAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T22:34:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ap.gov.br/detranap/wp-content/uploads/2026/04/requerimento-infracao.pdf","version_rank":1}'),
('SRC_AP_DETRAN_SOLICITACAO_SERVICOS_v1','SRC_AP_DETRAN_SOLICITACAO_SERVICOS','v1.0','7cd67e5be101a37aea5f9e1cb1d4823a6cfb4906b2b046f3cded7c9bf54f4c49','','https://www.detran.ap.gov.br/detranap/wp-content/uploads/2026/04/solicitacao-de-servicos.pdf','{"fase8_inventory_id":"SRC_AP_DETRAN_SOLICITACAO_SERVICOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T22:34:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ap.gov.br/detranap/wp-content/uploads/2026/04/solicitacao-de-servicos.pdf","version_rank":1}'),
('SRC_AL_CETRAN_RESOLUCAO_01_2000_v1','SRC_AL_CETRAN_RESOLUCAO_01_2000','v1.0','eb391d7f014c7d09950329b601bcc3152bcafa2097529daf98667c7302af75c0','','https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=68&catid=87&m=0','{"fase8_inventory_id":"SRC_AL_CETRAN_RESOLUCAO_01_2000","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:00:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=68&catid=87&m=0","version_rank":1}'),
('SRC_AL_CETRAN_RESOLUCAO_04_2002_v1','SRC_AL_CETRAN_RESOLUCAO_04_2002','v1.0','f5b987626dde593893ce794da517d15271ef140b16ca3e0ab854175cbdde9796','','https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=71&catid=87&m=0','{"fase8_inventory_id":"SRC_AL_CETRAN_RESOLUCAO_04_2002","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:01:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=71&catid=87&m=0","version_rank":1}'),
('SRC_AL_CETRAN_RESOLUCAO_02_2000_v1','SRC_AL_CETRAN_RESOLUCAO_02_2000','v1.0','2abb3ef1254836bf41eabf59c950fe2a80b7828e60d690dd2f4e63fc05ae06f0','','https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=69&catid=87&m=0','{"fase8_inventory_id":"SRC_AL_CETRAN_RESOLUCAO_02_2000","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:02:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.al.gov.br/legislacao/resolucoes?task=download.send&id=69&catid=87&m=0","version_rank":1}'),
('SRC_AM_DETRAN_PORTARIA_NORMATIVA_015_2026_v1','SRC_AM_DETRAN_PORTARIA_NORMATIVA_015_2026','v1.0','08add6a30898435dd9ab9ef4c16921d46fd4a79ab0ab9325ae0e9154ee14b020','','https://www.detran.am.gov.br/wp-content/uploads/2026/07/PORTARIA-NORMATIVA-No-015.pdf','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_NORMATIVA_015_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:30:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/07/PORTARIA-NORMATIVA-No-015.pdf","version_rank":1}'),
('SRC_AM_DETRAN_PORTARIA_NORMATIVA_014_2026_v1','SRC_AM_DETRAN_PORTARIA_NORMATIVA_014_2026','v1.0','84772aed1d7464653f236b6e4d8fde92325de0f303687da7845a24e361a4f057','','https://www.detran.am.gov.br/wp-content/uploads/2026/07/PORTARIA-NORMATIVA-No-014.pdf','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_NORMATIVA_014_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:31:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/07/PORTARIA-NORMATIVA-No-014.pdf","version_rank":1}'),
('SRC_AM_MEMO_753_2026_RECUPERADO_v1','SRC_AM_MEMO_753_2026_RECUPERADO','v1.0','59b023ada37e71cdb21c2ed4be9dca59ec2c5cf54323f0e2c1f001deb8434439','','https://www.detran.am.gov.br/wp-content/uploads/2026/09/MEMO_N_753_2026_OPTRAN_DETRAN_Portaria.pdf','{"fase8_inventory_id":"SRC_AM_MEMO_753_2026_RECUPERADO","collection_state":"RECUPERADO","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T20:39:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/09/MEMO_N_753_2026_OPTRAN_DETRAN_Portaria.pdf","recovered":true,"version_rank":1}'),
('SRC_AM_DETRAN_PORTARIA_01_03_011210_078105_2026_96_v1','SRC_AM_DETRAN_PORTARIA_01_03_011210_078105_2026_96','v1.0','5192f8b88dc0466a0993b667eb4f05b209bde835368d19aa3d8765cdf1c637c3','','https://www.detran.am.gov.br/wp-content/uploads/2026/08/01.03.011210.078105_2026_96_Portaria.pdf','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_01_03_011210_078105_2026_96","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:33:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/08/01.03.011210.078105_2026_96_Portaria.pdf","version_rank":1}'),
('SRC_AM_DETRAN_PORTARIA_01_03_011210_083647_2026_80_v1','SRC_AM_DETRAN_PORTARIA_01_03_011210_083647_2026_80','v1.0','82e54883faf4d63177788b9ff629d8b0907a6a98cb50e2d81b129471ed3af0de','','https://www.detran.am.gov.br/wp-content/uploads/2026/08/01.03.011210.083647_2026_80_Portaria.pdf','{"fase8_inventory_id":"SRC_AM_DETRAN_PORTARIA_01_03_011210_083647_2026_80","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-23T23:34:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.am.gov.br/wp-content/uploads/2026/08/01.03.011210.083647_2026_80_Portaria.pdf","version_rank":1}'),
('SRC_CE_DETRAN_INSTRUCAO_SERVICO_004_2007_COHAB_v1','SRC_CE_DETRAN_INSTRUCAO_SERVICO_004_2007_COHAB','v1.0','176f2ff596d4c54cb170acc2817952a17842ae0766ef206751caa9c302efba74','','https://www.ce.gov.br/detran/wp-content/uploads/sites/91/2010/06/is004_2007_cohab.pdf','{"fase8_inventory_id":"SRC_CE_DETRAN_INSTRUCAO_SERVICO_004_2007_COHAB","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/wp-content/uploads/sites/91/2010/06/is004_2007_cohab.pdf","version_rank":1}')
on conflict (id) do nothing;
insert into knowledge_document_versions (id,document_id,version,content_hash,content,source_url,metadata) values
('SRC_CE_DETRAN_DEFESA_AUTUAR_INFRACAO_v1','SRC_CE_DETRAN_DEFESA_AUTUAR_INFRACAO','v1.0','ebaded0d43931826c3a02c1527d57fe916bbc4ec78d24dbf304020ece1ea818a','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_DETRAN_DEFESA_AUTUAR_INFRACAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","version_rank":1}'),
('SRC_CE_DETRAN_RECURSO_JARI_v1','SRC_CE_DETRAN_RECURSO_JARI','v1.0','ebaded0d43931826c3a02c1527d57fe916bbc4ec78d24dbf304020ece1ea818a','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_DETRAN_RECURSO_JARI","collection_state":"DUPLICATA_EXATA","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","duplicate_of":"SRC_CE_DETRAN_DEFESA_AUTUAR_INFRACAO","version_rank":1}'),
('SRC_CE_CETRAN_REGIMENTO_INTERNO_2020_v1','SRC_CE_CETRAN_REGIMENTO_INTERNO_2020','v1.0','676bbd60f4379d8641a132c41fbe5a77b5692ec2cd219808e6b1d3795e1e13c6','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_CETRAN_REGIMENTO_INTERNO_2020","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","version_rank":1}'),
('SRC_CE_CETRAN_RESOLUCAO_001_2013_v1','SRC_CE_CETRAN_RESOLUCAO_001_2013','v1.0','6e2835b007ad87f393623aa1e3095daf9eeb6a9560a0f59d55acbd48d08c8712','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_001_2013","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","version_rank":1}'),
('SRC_CE_CETRAN_RESOLUCAO_001_2014_v1','SRC_CE_CETRAN_RESOLUCAO_001_2014','v1.0','27aa5bc7b7ad3bff97fbaf336a0bf72a4dca9244b3a4e68dfb69bab8a3cf15aa','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_001_2014","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","version_rank":1}'),
('SRC_CE_CETRAN_RESOLUCAO_003_2019_v1','SRC_CE_CETRAN_RESOLUCAO_003_2019','v1.0','8825a645a52be3e5a5428b3f9929d48c946a60536970d4f8d1ec597e5661590d','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_003_2019","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","version_rank":1}'),
('SRC_CE_CETRAN_RESOLUCAO_005_v1','SRC_CE_CETRAN_RESOLUCAO_005','v1.0','805fcf53c4e2abf2386fa3956de7c2b755c5b0aa22d3550ba073c6aedc3be7ec','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_005","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","version_rank":1}'),
('SRC_CE_CETRAN_RESOLUCAO_006_v1','SRC_CE_CETRAN_RESOLUCAO_006','v1.0','de170addd262bd41704f5143169d4afa7b9d90471411252af1487f2d5284b5a3','','https://www.ce.gov.br/detran/','{"fase8_inventory_id":"SRC_CE_CETRAN_RESOLUCAO_006","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T00:12:29Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.ce.gov.br/detran/","version_rank":1}'),
('SRC_ES_DETRAN_RECURSO_MULTA_ONLINE_v1','SRC_ES_DETRAN_RECURSO_MULTA_ONLINE','v1.0','0cc85439233035f6bd95e4a20cbc72c2cc78a70758c5710aad7041b938dd49b4','','https://detran.es.gov.br/recurso-de-multa-online','{"fase8_inventory_id":"SRC_ES_DETRAN_RECURSO_MULTA_ONLINE","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T01:37:56Z","content_state":"NOT_STORED_FASE9","origin_url":"https://detran.es.gov.br/recurso-de-multa-online","version_rank":1}'),
('SRC_ES_CETRAN_RESOLUCAO_20_2026_v1','SRC_ES_CETRAN_RESOLUCAO_20_2026','v1.0','5e59fc8be7ef37d6076db98210e1135820f9c08d0481cc3df806881d559bfae9','','https://detran.es.gov.br/Media/detran/Legislacao/Resoluções/RESOLUÇÃO%20CETRAN%20Nº%2020-2026.pdf','{"fase8_inventory_id":"SRC_ES_CETRAN_RESOLUCAO_20_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T01:37:56Z","content_state":"NOT_STORED_FASE9","origin_url":"https://detran.es.gov.br/Media/detran/Legislacao/Resoluções/RESOLUÇÃO%20CETRAN%20Nº%2020-2026.pdf","version_rank":1}'),
('SRC_GO_DETRAN_DEFESA_PREVIA_PF_v1','SRC_GO_DETRAN_DEFESA_PREVIA_PF','v1.0','0cccd1e18e850ae8279470c8900c34d3dc692eaf08b7178e445aa88f920c12d1','','https://www.detran.go.gov.br/','{"fase8_inventory_id":"SRC_GO_DETRAN_DEFESA_PREVIA_PF","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T02:50:55Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.go.gov.br/","version_rank":1}'),
('SRC_GO_CETRAN_RESOLUCAO_1999_003_v1','SRC_GO_CETRAN_RESOLUCAO_1999_003','v1.0','c6736863bc740f08d66104dd4081cb8bbbd439619e4d7bf75dde0f1dc02af511','','https://www.cetran.go.gov.br/','{"fase8_inventory_id":"SRC_GO_CETRAN_RESOLUCAO_1999_003","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T02:51:31Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.go.gov.br/","version_rank":1}')
on conflict (id) do nothing;
insert into knowledge_document_versions (id,document_id,version,content_hash,content,source_url,metadata) values
('SRC_MG_DETRAN_DEFESA_PREVIA_PF_v1','SRC_MG_DETRAN_DEFESA_PREVIA_PF','v1.0','f0cbb02f78607f29809b718620ecc268a169b5382a0562215d21a24d1a227c91','','https://www.detran.mg.gov.br/infracoes/multa/apresentar-defesa-previa-infracao-1','{"fase8_inventory_id":"SRC_MG_DETRAN_DEFESA_PREVIA_PF","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T14:31:34Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.mg.gov.br/infracoes/multa/apresentar-defesa-previa-infracao-1","version_rank":1}'),
('SRC_MS_DETRAN_PORTARIA_211_2026_v1','SRC_MS_DETRAN_PORTARIA_211_2026','v1.0','a00ac1712a499b4d04214c1dfad00e136a842b1437d158a449ad0d5304985cd6','','https://www.detran.ms.gov.br/wp-content/uploads/2026/06/PORTARIA-DETRANMS-N-No-211-DE-18-DE-JUNHO-DE-2026.pdf','{"fase8_inventory_id":"SRC_MS_DETRAN_PORTARIA_211_2026","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:19:44Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.ms.gov.br/wp-content/uploads/2026/06/PORTARIA-DETRANMS-N-No-211-DE-18-DE-JUNHO-DE-2026.pdf","version_rank":1}'),
('SRC_MS_CETRAN_REGIMENTO_INTERNO_v1','SRC_MS_CETRAN_REGIMENTO_INTERNO','v1.0','55b474d84c0daa8a733cc0cc3f2e80682144762ffd3800e09813a4457193bdc5','','https://www.sejusp.ms.gov.br/wp-content/uploads/2025/11/Regimento-Interno-CETRAN.pdf','{"fase8_inventory_id":"SRC_MS_CETRAN_REGIMENTO_INTERNO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:19:46Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.sejusp.ms.gov.br/wp-content/uploads/2025/11/Regimento-Interno-CETRAN.pdf","version_rank":1}'),
('SRC_PA_DETRAN_PORTAL_v1','SRC_PA_DETRAN_PORTAL','v1.0','d138c2e598299b6d0afd9a56b2a651f47e374d33c28b462e21b94fe9351191cf','','https://www.detran.pa.gov.br/','{"fase8_inventory_id":"SRC_PA_DETRAN_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:29:16Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.pa.gov.br/","version_rank":1}'),
('SRC_PB_DETRAN_DEFESA_RECURSOS_ONLINE_v1','SRC_PB_DETRAN_DEFESA_RECURSOS_ONLINE','v1.0','1914ae55909266741a03e0911c257cbbc1f66ea04296335675f96c51b5a6e573','','https://detran.pb.gov.br/infracoes/recursos-defesa-online','{"fase8_inventory_id":"SRC_PB_DETRAN_DEFESA_RECURSOS_ONLINE","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:32:16Z","content_state":"NOT_STORED_FASE9","origin_url":"https://detran.pb.gov.br/infracoes/recursos-defesa-online","version_rank":1}'),
('SRC_PB_CETRAN_REGIMENTO_INTERNO_v1','SRC_PB_CETRAN_REGIMENTO_INTERNO','v1.0','1bcb4fcc7b251e00d7569968715b02d9ed44507704db28a37912c5cd876ecbd2','','https://www.cetran.pb.gov.br/legislacao/Regimento%20interno/@@download/file/Safari.pdf','{"fase8_inventory_id":"SRC_PB_CETRAN_REGIMENTO_INTERNO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:32:20Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.pb.gov.br/legislacao/Regimento%20interno/@@download/file/Safari.pdf","version_rank":1}'),
('SRC_PI_DETRAN_MULTAS_ART320_v1','SRC_PI_DETRAN_MULTAS_ART320','v1.0','582c2690a672dc0fc68d5a3b76ea2d1686a889a9689f9b04e3d9c036adeeabee','','https://portal.pi.gov.br/detran/multas-de-transito-detran-pi-art-320-do-ctb/','{"fase8_inventory_id":"SRC_PI_DETRAN_MULTAS_ART320","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:36:21Z","content_state":"NOT_STORED_FASE9","origin_url":"https://portal.pi.gov.br/detran/multas-de-transito-detran-pi-art-320-do-ctb/","version_rank":1}'),
('SRC_PI_DETRAN_RECURSO_MULTA_v1','SRC_PI_DETRAN_RECURSO_MULTA','v1.0','9f9afcb1f1dce76e529d870f7f1a22f7c5a4f592287685b93a747a8285726f0c','','https://www.pi.getran.com.br/site/apps/multa/recurso/cadastrar-recurso.jsp','{"fase8_inventory_id":"SRC_PI_DETRAN_RECURSO_MULTA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:36:21Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.pi.getran.com.br/site/apps/multa/recurso/cadastrar-recurso.jsp","version_rank":1}'),
('SRC_PI_CETRAN_DECRETO_22731_2024_v1','SRC_PI_CETRAN_DECRETO_22731_2024','v1.0','8f1a3e2db72becc6e2a972f769a454e34327179cab5a02ad7a04b67dfeb7d922','','https://portal.pi.gov.br/detran/wp-content/uploads/sites/62/2025/11/DECRETO-No-22.731-DE-02-DE-FEVEREIRO-DE-2024.pdf','{"fase8_inventory_id":"SRC_PI_CETRAN_DECRETO_22731_2024","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:37:24Z","content_state":"NOT_STORED_FASE9","origin_url":"https://portal.pi.gov.br/detran/wp-content/uploads/sites/62/2025/11/DECRETO-No-22.731-DE-02-DE-FEVEREIRO-DE-2024.pdf","version_rank":1}'),
('SRC_PI_CETRAN_DECRETO_24023_2025_v1','SRC_PI_CETRAN_DECRETO_24023_2025','v1.0','ddb7054313ef87af8e04b75b9795887401e2f447f887a9a11def169cb153eced','','https://portal.pi.gov.br/detran/wp-content/uploads/sites/62/2025/11/DECRETO-No-24.023-DE-19-DE-AGOSTO-DE-2025.pdf','{"fase8_inventory_id":"SRC_PI_CETRAN_DECRETO_24023_2025","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:37:24Z","content_state":"NOT_STORED_FASE9","origin_url":"https://portal.pi.gov.br/detran/wp-content/uploads/sites/62/2025/11/DECRETO-No-24.023-DE-19-DE-AGOSTO-DE-2025.pdf","version_rank":1}'),
('SRC_PR_DETRAN_RECURSOS_v1','SRC_PR_DETRAN_RECURSOS','v1.0','2e73369a4e953b449d41762b7288afb49c54046e3bc53a07ee7fc2b635b958e0','','https://www.detran.pr.gov.br/Pagina/Recursos','{"fase8_inventory_id":"SRC_PR_DETRAN_RECURSOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:39:05Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.pr.gov.br/Pagina/Recursos","version_rank":1}'),
('SRC_PR_CETRAN_RESOLUCOES_v1','SRC_PR_CETRAN_RESOLUCOES','v1.0','051a5587291d4448ac1560096b4f06cc4f6cee47bb44427faaf2ee303d4a86c4','','https://www.cetran.pr.gov.br/Pagina/Resolucoes','{"fase8_inventory_id":"SRC_PR_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:39:05Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.pr.gov.br/Pagina/Resolucoes","version_rank":1}')
on conflict (id) do nothing;
insert into knowledge_document_versions (id,document_id,version,content_hash,content,source_url,metadata) values
('SRC_PR_CETRAN_RESOLUCAO_077_2021_v1','SRC_PR_CETRAN_RESOLUCAO_077_2021','v1.0','ec783fd23c79bd4e6755a031fd9617fa8b05da90f087d28eb36a7d431f821d51','','https://www.cetran.pr.gov.br/sites/cetran/arquivos_restritos/files/documento/2021-11/resolucao_077_-21_regras_e_procedimentos_para_a_fiscalizacao_de_transito_dos_ciclomotores_cicloeletricos_e_equiparados.pdf','{"fase8_inventory_id":"SRC_PR_CETRAN_RESOLUCAO_077_2021","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:39:05Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.pr.gov.br/sites/cetran/arquivos_restritos/files/documento/2021-11/resolucao_077_-21_regras_e_procedimentos_para_a_fiscalizacao_de_transito_dos_ciclomotores_cicloeletricos_e_equiparados.pdf","version_rank":1}'),
('SRC_RJ_DETRAN_FORMULARIOS_INFRACOES_v1','SRC_RJ_DETRAN_FORMULARIOS_INFRACOES','v1.0','9faad6e62aaddccd2e504156d52be5829a532733b8d1b6b3a4821fdb9ec38b67','','https://www.detran.rj.gov.br/formulario/formularios-de-infracoes','{"fase8_inventory_id":"SRC_RJ_DETRAN_FORMULARIOS_INFRACOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:41:00Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rj.gov.br/formulario/formularios-de-infracoes","version_rank":1}'),
('SRC_RJ_DETRAN_FORMULARIO_DEFESA_RECURSO_v1','SRC_RJ_DETRAN_FORMULARIO_DEFESA_RECURSO','v1.0','f0c237b48a530ef10988dd4f95c5c7864ca31d4692b7bb1f051cb710350bf11f','','https://www.detran.rj.gov.br/images/ascom/pdf/formularios/CJC0160_apresentacao_defesa_recurso.pdf','{"fase8_inventory_id":"SRC_RJ_DETRAN_FORMULARIO_DEFESA_RECURSO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:41:01Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rj.gov.br/images/ascom/pdf/formularios/CJC0160_apresentacao_defesa_recurso.pdf","version_rank":1}'),
('SRC_RJ_CETRAN_RESOLUCOES_v1','SRC_RJ_CETRAN_RESOLUCOES','v1.0','01812bab2ee1d80fe13131cfdf56e863659c0b8d4646c6204edc76749378df2a','','http://www.cetran.rj.gov.br/estadual/resolucoes-cetran','{"fase8_inventory_id":"SRC_RJ_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:41:00Z","content_state":"NOT_STORED_FASE9","origin_url":"http://www.cetran.rj.gov.br/estadual/resolucoes-cetran","version_rank":1}'),
('SRC_RR_DETRAN_DEFESA_PREVIA_v1','SRC_RR_DETRAN_DEFESA_PREVIA','v1.0','e437a867c46791606da81b18e421760e92ba59ce12195497fe669f46d6addf34','','https://www.detran.rr.gov.br/infracoes/informacoes/multas-em-fase-de-autuacao-defesa-previa/','{"fase8_inventory_id":"SRC_RR_DETRAN_DEFESA_PREVIA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:47:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rr.gov.br/infracoes/informacoes/multas-em-fase-de-autuacao-defesa-previa/","version_rank":1}'),
('SRC_RR_DETRAN_RECURSO_AUTUACAO_DEFESA_v1','SRC_RR_DETRAN_RECURSO_AUTUACAO_DEFESA','v1.0','72bca3ce26f57d945a79c071db8f1edd1d48941043a5cda46c921e39f4c30f92','','https://www.detran.rr.gov.br/wp-content/uploads/2022/07/recurso_de_autuacao_-_defesa_previa.pdf','{"fase8_inventory_id":"SRC_RR_DETRAN_RECURSO_AUTUACAO_DEFESA","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:47:50Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rr.gov.br/wp-content/uploads/2022/07/recurso_de_autuacao_-_defesa_previa.pdf","version_rank":1}'),
('SRC_RR_DETRAN_RECURSO_CETRAN_v1','SRC_RR_DETRAN_RECURSO_CETRAN','v1.0','66207d91e9862d398d1aabcfa37f86682012ada90cfe636eee989cde5be4bb94','','https://www.detran.rr.gov.br/wp-content/uploads/2022/07/recurso_ao_CETRAN_-_RR.pdf','{"fase8_inventory_id":"SRC_RR_DETRAN_RECURSO_CETRAN","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"application/pdf","retrieved_at":"2026-09-24T15:47:51Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rr.gov.br/wp-content/uploads/2022/07/recurso_ao_CETRAN_-_RR.pdf","version_rank":1}'),
('SRC_RS_DETRAN_APRESENTAR_DEFESA_RECURSO_v1','SRC_RS_DETRAN_APRESENTAR_DEFESA_RECURSO','v1.0','f3e49ba08f80a3d317d69ea7d7b65f63df117ae2c897d75bd925fb1c5d29f1d3','','https://www.detran.rs.gov.br/apresentar-defesa-e-recurso','{"fase8_inventory_id":"SRC_RS_DETRAN_APRESENTAR_DEFESA_RECURSO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:50:39Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.rs.gov.br/apresentar-defesa-e-recurso","version_rank":1}'),
('SRC_RS_CETRAN_RESOLUCOES_v1','SRC_RS_CETRAN_RESOLUCOES','v1.0','e18ad19d629fc7fca869de819f4da0578f4d397cd48cd8302189d4a56e715e47','','https://www.cetran.rs.gov.br/resolucoes','{"fase8_inventory_id":"SRC_RS_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:50:39Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.rs.gov.br/resolucoes","version_rank":1}'),
('SRC_SC_DETRAN_MULTAS_PENALIDADES_v1','SRC_SC_DETRAN_MULTAS_PENALIDADES','v1.0','c8714689934c206696680fb2d5d1c41df77154168b8eb457b6b3bbe663d5b9a2','','https://www.detran.sc.gov.br/multas-e-penalidades/','{"fase8_inventory_id":"SRC_SC_DETRAN_MULTAS_PENALIDADES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:52:59Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.sc.gov.br/multas-e-penalidades/","version_rank":1}'),
('SRC_SC_DETRAN_DEFESA_AUTUACAO_v1','SRC_SC_DETRAN_DEFESA_AUTUACAO','v1.0','0bfe2171ae4bc0ce082a21d086b42ee4288d44c7dc0433342a7daeb72cbc028e','','https://www.detran.sc.gov.br/defesa-de-autuacao/','{"fase8_inventory_id":"SRC_SC_DETRAN_DEFESA_AUTUACAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:52:59Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.sc.gov.br/defesa-de-autuacao/","version_rank":1}'),
('SRC_SC_CETRAN_RESOLUCOES_v1','SRC_SC_CETRAN_RESOLUCOES','v1.0','029b4d9f5c46d0e9abda66cdf2f83ca46d48c6e6a5621f43ae702a52ff888f24','','https://cetran.sc.gov.br/resolucoes/','{"fase8_inventory_id":"SRC_SC_CETRAN_RESOLUCOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:52:59Z","content_state":"NOT_STORED_FASE9","origin_url":"https://cetran.sc.gov.br/resolucoes/","version_rank":1}')
on conflict (id) do nothing;
insert into knowledge_document_versions (id,document_id,version,content_hash,content,source_url,metadata) values
('SRC_SP_DETRAN_PORTAL_DETRANSP_v1','SRC_SP_DETRAN_PORTAL_DETRANSP','v1.0','9a406ad41cf171461e9ae0b968088c433df193f097dfb9aef0d91a58019e8d26','','https://www.detran.sp.gov.br/detransp','{"fase8_inventory_id":"SRC_SP_DETRAN_PORTAL_DETRANSP","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:58:53Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.detran.sp.gov.br/detransp","version_rank":1}'),
('SRC_SP_CETRAN_LEGISLACOES_v1','SRC_SP_CETRAN_LEGISLACOES','v1.0','9c07d6e3888e386714707f4af1ccb884dfa7004d7ca69fbb1dd8ee3ae3b524c1','','https://www.cetran.sp.gov.br/CetranWeb/institucional/legislacoes','{"fase8_inventory_id":"SRC_SP_CETRAN_LEGISLACOES","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:58:53Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.sp.gov.br/CetranWeb/institucional/legislacoes","version_rank":1}'),
('SRC_SP_CETRAN_ATOS_NORMATIVOS_v1','SRC_SP_CETRAN_ATOS_NORMATIVOS','v1.0','28ebdd2f959c71454fa1e51163c9fc3cc290b212a95709684e63890f300c7232','','https://www.cetran.sp.gov.br/CetranWeb/atosnormativos','{"fase8_inventory_id":"SRC_SP_CETRAN_ATOS_NORMATIVOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T15:58:53Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.cetran.sp.gov.br/CetranWeb/atosnormativos","version_rank":1}'),
('SRC_TO_DETRAN_PORTAL_v1','SRC_TO_DETRAN_PORTAL','v1.0','0345b86e82372b3ef60c2d8f28d1fb89b8d9ee2dc0b82a5f0e95f8792e97294f','','https://www.to.gov.br/detran/','{"fase8_inventory_id":"SRC_TO_DETRAN_PORTAL","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T16:01:07Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.to.gov.br/detran/","version_rank":1}'),
('SRC_TO_DETRAN_FORMULARIO_RECURSOS_v1','SRC_TO_DETRAN_FORMULARIO_RECURSOS','v1.0','03ca65ebe74a3b75cc2a3c8f9d1832f45c7d8d3ec847622999016f2d4adaa50a','','https://www.to.gov.br/detran/formulario-de-recursos/252b8affcn93','{"fase8_inventory_id":"SRC_TO_DETRAN_FORMULARIO_RECURSOS","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T16:01:07Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.to.gov.br/detran/formulario-de-recursos/252b8affcn93","version_rank":1}'),
('SRC_TO_DETRAN_RECURSO_MULTAS_CIDADAO_v1','SRC_TO_DETRAN_RECURSO_MULTAS_CIDADAO','v1.0','8e334838abb447aac5c0955edf55996e9459d402dde3181d93b005316148e419','','https://www.to.gov.br/detran/recurso-de-multas-portal-cidadao/77a9q0bazri','{"fase8_inventory_id":"SRC_TO_DETRAN_RECURSO_MULTAS_CIDADAO","collection_state":"COLLECTED","legal_status":"UNKNOWN","publication_date_known":false,"effective_state":"UNKNOWN","mime_hint":"text/html","retrieved_at":"2026-09-24T16:01:07Z","content_state":"NOT_STORED_FASE9","origin_url":"https://www.to.gov.br/detran/recurso-de-multas-portal-cidadao/77a9q0bazri","version_rank":1}')
on conflict (id) do nothing;
-- Aponta cada documento para sua versão v1 (DEFERRABLE FK).
update knowledge_documents d set current_version_id = v.id
from knowledge_document_versions v
where v.document_id = d.id and d.current_version_id is null;

-- Validação pós-carga (esperado: sources=39, documents=66, versions=66, sem_versao=0):
select (select count(*) from knowledge_sources) as sources,
       (select count(*) from knowledge_documents) as documents,
       (select count(*) from knowledge_document_versions) as versions,
       (select count(*) from knowledge_documents d where d.current_version_id is null) as sem_versao;
