/**
 * @file ctb-articles.ts
 * DefesaAI — Structured CTB Legal Database (Fase 3)
 * Comprehensive database of essential Brazilian Traffic Code articles,
 * requirements, nullity conditions, and procedural mandates.
 */

import { CtbArticleModel } from '../domain/knowledge-schema';

export const CTB_ARTICLES_DB: CtbArticleModel[] = [
  {
    article: 'Art. 280',
    title: 'Requisitos Formais de Validade do Auto de Infração de Trânsito',
    caput: 'Ocorrendo infração prevista na legislação de trânsito, lavrar-se-á auto de infração, do qual constará: I - tipificação da infração; II - local, data e hora do cometimento da infração; III - caracteres da placa de identificação do veículo, sua marca e espécie, e outros elementos julgados necessários à sua identificação; IV - o prontuário do condutor, sempre que possível; V - identificação do órgão ou entidade e da autoridade ou do agente autuador ou equipamento que comprovar a infração; VI - assinatura do infrator, sempre que possível.',
    paragraphsAndIncidents: [
      '§2º A infração deverá ser comprovada por declaração da autoridade ou do agente da autoridade de trânsito, por aparelho eletrônico ou por equipamento audiovisual, reações químicas ou qualquer outro meio tecnologicamente disponível, previamente regulamentado pelo CONTRAN.',
      '§4º O agente da autoridade de trânsito competente para lavrar o auto de infração poderá ser servidor civil, estatutário ou celetista ou, ainda, policial militar designado pela autoridade de trânsito com jurisdição sobre a via.',
    ],
    practicalApplication: 'Serve como fundamento primordial para anulação de autos com preenchimento incompleto, omissão do local exato, falta de matrícula do agente, erro de placa ou ausência de regulamentação do equipamento eletrônico.',
    nullityConsequence: 'Nulidade absoluta do AIT por vício formal insanável (Art. 281, parágrafo único, I do CTB).',
    relatedResolutions: ['Resolução CONTRAN nº 985/2022 (MBFT)', 'Portaria SENATRAN nº 354/2022'],
  },
  {
    article: 'Art. 281',
    title: 'Julgamento da Consistência do AIT e Decadência de 30 Dias',
    caput: 'A autoridade de trânsito, na esfera da competência estabelecida neste Código e dentro de sua circunscrição, julgará a consistência do auto de infração e aplicará a penalidade cabível.',
    paragraphsAndIncidents: [
      'Parágrafo único. O auto de infração será arquivado e seu registro julgado insubsistente:',
      'I - se considerado inconsistente ou irregular;',
      'II - se, no prazo máximo de trinta dias, não for expedida a notificação da autuação.',
    ],
    practicalApplication: 'Regra de ouro do direito de trânsito. Se a Notificação de Autuação (NA) for postada ou expedida após 30 dias contados da data da infração, opera-se a decadência do direito punitivo do Estado.',
    nullityConsequence: 'Arquivamento compulsório e cancelamento de todos os efeitos administrativos e financeiros.',
    relatedResolutions: ['Resolução CONTRAN nº 918/2022', 'Súmula 312 do STJ'],
  },
  {
    article: 'Art. 282',
    title: 'Notificação da Imposição de Penalidade (NP) e Garantia Recursal',
    caput: 'Aplicada a penalidade, será expedida notificação ao proprietário do veículo ou ao infrator, por remessa postal ou por qualquer outro meio tecnológico hábil, que assegure a ciência da imposição da penalidade.',
    paragraphsAndIncidents: [
      '§4º Da notificação deverá constar a data do término do prazo para apresentação de recurso pelo responsável pela infração, que não será inferior a trinta dias contados da data da notificação da penalidade.',
      '§6º O prazo para expedição da notificação da penalidade é de 180 (cento e oitenta) dias se houver defesa prévia, ou 360 (trezentos e sessenta) dias se não houver, sob pena de decadência.',
    ],
    practicalApplication: 'Garante o direito a prazo recursal não inferior a 30 dias para recurso à JARI e estabelece decadência expressa para expedição da Notificação de Penalidade.',
    nullityConsequence: 'Extinção da punibilidade e nulidade do procedimento por cerceamento de defesa.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022', 'Resolução CONTRAN nº 918/2022'],
  },
  {
    article: 'Art. 267',
    title: 'Direito Subjetivo à Conversão de Multa em Advertência por Escrito',
    caput: 'Deverá ser imposta a penalidade de advertência por escrito para as infrações de natureza leve ou média, passíveis de serem punidas com multa, caso o infrator não tenha cometido nenhuma outra infração nos últimos 12 (doze) meses.',
    paragraphsAndIncidents: [
      'Alterado pela Lei nº 14.071/2020: substituiu a expressão "poderá ser imposta" por "deverá ser imposta", transformando o ato em direito subjetivo vinculado da parte.',
    ],
    practicalApplication: 'Para qualquer infração de 3 pontos (leve) ou 4 pontos (média), o condutor sem histórico nos últimos 12 meses tem 100% de direito à isenção da multa e cancelamento dos pontos.',
    nullityConsequence: 'Indeferimento ilegal passível de mandado de segurança ou recurso ao CETRAN.',
    relatedResolutions: ['Resolução CONTRAN nº 918/2022, Art. 10'],
  },
  {
    article: 'Art. 285',
    title: 'Recurso à JARI e Concessão Obrigatória de Efeito Suspensivo',
    caput: 'O recurso contra a penalidade de multa imposta será interposto perante a autoridade que a aplicou, a qual o remeterá à JARI, no prazo de até 10 (dez) dias úteis.',
    paragraphsAndIncidents: [
      '§3º Se, por motivo de força maior, o recurso não for julgado dentro do prazo de 24 (vinte e quatro) meses, a autoridade que impôs a penalidade, de ofício, ou por solicitação do recorrente, concederá efeito suspensivo (Redação dada pela Lei nº 14.229/2021).',
    ],
    practicalApplication: 'Garante que durante o trâmite do recurso à JARI o condutor não sofra bloqueio no licenciamento, restrição no Renavam ou suspensão da CNH.',
    nullityConsequence: 'Efeito suspensivo de pleno direito até julgamento final em última instância.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022'],
  },
  {
    article: 'Art. 288',
    title: 'Recurso ao CETRAN e Encerramento da Instância Administrativa',
    caput: 'Das decisões da JARI cabe recurso a ser interposto, no prazo de trinta dias contado da publicação ou da notificação da decisão.',
    paragraphsAndIncidents: [
      'Art. 289. O recurso de que trata o art. 288 será julgado no prazo de vinte e quatro meses pelo CETRAN ou pelo CONTRANDIFE.',
    ],
    practicalApplication: 'Segunda e última instância no âmbito administrativo do Sistema Nacional de Trânsito.',
    nullityConsequence: 'Impossibilidade de exigibilidade da penalidade antes do julgamento final pelo órgão colegiado.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022'],
  },
  {
    article: 'Art. 90',
    title: 'Inexigibilidade de Sanção por Sinalização Insuficiente ou Incorreta',
    caput: 'Não serão aplicadas as sanções previstas neste Código por inobservância à sinalização quando esta for insuficiente ou incorreta.',
    paragraphsAndIncidents: [
      '§1º O órgão ou entidade de trânsito com circunscrição sobre a via é responsável pela implantação da sinalização, respondendo pela sua falta, insuficiência ou incorreta colocação.',
    ],
    practicalApplication: 'Defesa fundamental para multas de radar sem placa R-19, semáforo encoberto por árvores, faixa de pedestre apagada ou placas em desacordo com os manuais de tráfego.',
    nullityConsequence: 'Atipicidade material e cancelamento da autuação.',
    relatedResolutions: ['Resolução CONTRAN nº 798/2020', 'Resolução CONTRAN nº 973/2022'],
  },
  {
    article: 'Art. 218',
    title: 'Infrações por Excesso de Velocidade e Gradação de Gravidade',
    caput: 'Transitar em velocidade superior à máxima permitida para o local, medida por instrumento ou equipamento hábil, em rodovias, vias de trânsito rápido, vias arteriais e demais vias:',
    paragraphsAndIncidents: [
      'I - quando a velocidade for superior à máxima em até vinte por cento: Infração média (4 pontos, R$ 130,16);',
      'II - quando a velocidade for superior à máxima em mais de vinte por cento até cinquenta por cento: Infração grave (5 pontos, R$ 195,23);',
      'III - quando a velocidade for superior à máxima em mais de cinquenta por cento: Infração gravíssima (3x, R$ 880,41, e suspensão imediata do direito de dirigir).',
    ],
    practicalApplication: 'A apuração depende impreterivelmente de medição por equipamento homologado pelo INMETRO com margem de tolerância deduzida (velocidade considerada).',
    nullityConsequence: 'Nulidade se o radar não possuir laudo válido de até 12 meses ou se a tolerância metrológica rebaixar o enquadramento.',
    relatedResolutions: ['Resolução CONTRAN nº 798/2020', 'Portaria INMETRO nº 158/2022'],
  },
  {
    article: 'Art. 165 e 165-A',
    title: 'Lei Seca: Condução sob Efeito de Álcool e Recusa ao Teste',
    caput: 'Art. 165. Dirigir sob a influência de álcool ou de qualquer outra substância psicoativa. Art. 165-A. Recusar-se a ser submetido a teste, exame clínico, perícia ou outro procedimento que permita certificar influência de álcool.',
    paragraphsAndIncidents: [
      'Penalidade: Infração gravíssima (fator 10x - R$ 2.934,70) e suspensão do direito de dirigir por 12 (doze) meses.',
      'Obrigatória aplicação da Resolução CONTRAN nº 432/2013 para verificação de margem metrológica ou preenchimento do Termo de Constatação de Sinais.',
    ],
    practicalApplication: 'A recusa ao bafômetro isoladamente não dispensa o agente de lavrar o termo descritivo de sinais clínicos do Anexo II da Res. 432.',
    nullityConsequence: 'Anulação integral do auto e do processo suspensivo por ausência de prova de materialidade.',
    relatedResolutions: ['Resolução CONTRAN nº 432/2013', 'Portaria INMETRO nº 369/2021'],
  },
  {
    article: 'Art. 252',
    title: 'Uso de Telefone Celular ao Volante',
    caput: 'Dirigir o veículo: VI - utilizando-se de fones nos ouvidos conectados a aparelhagem sonora ou de telefone celular;',
    paragraphsAndIncidents: [
      'Parágrafo único. A hipótese prevista no inciso V caracterizar-se-á como infração gravíssima no caso de o condutor estar segurando ou manuseando telefone celular.',
    ],
    practicalApplication: 'Distingue-se entre condutor manuseando aparelho solto e o uso de suporte veicular para navegação GPS ou comando de voz.',
    nullityConsequence: 'Falta de descrição detalhada das circunstâncias fáticas pelo agente anula a autuação (Res. 985/2022).',
    relatedResolutions: ['Resolução CONTRAN nº 985/2022 (MBFT - Ficha 736-62)'],
  },
  {
    article: 'Art. 208',
    title: 'Avanço de Sinal Vermelho e Parada Obrigatória',
    caput: 'Avançar o sinal vermelho do semáforo ou, onde houver, o de parada obrigatória:',
    paragraphsAndIncidents: [
      'Penalidade: multa (gravíssima) e 7 (sete) pontos na CNH.',
      'Inciso I: Avançar o sinal vermelho do semáforo.',
      'Inciso II: Parar o veículo sobre a faixa de pedestres na mudança de sinal luminoso.',
      'Inciso III: Transpor, sem autorização, bloqueio viário policial.',
    ],
    practicalApplication: 'Verificar tempo de sinal amarelo (Res. 973/2022), visibilidade do semáforo, dilema do amarelo, e se houve parada obrigatória em faixa.',
    nullityConsequence: 'Anulação se tempo de amarelo insuficiente, sinalização encoberta, ou inexistência de dilema do amarelo configurado.',
    relatedResolutions: ['Resolução CONTRAN nº 973/2022 (Sinalização Semafórica)', 'Resolução CONTRAN nº 985/2022 (MBFT)'],
  },
  {
    article: 'Art. 162',
    title: 'Dirigir sem CNH ou com CNH Cassada/Suspensa',
    caput: 'Dirigir veículo automotor: I - sem possuir Carteira Nacional de Habilitação ou Permissão para Dirigir; II - com Carteira Nacional de Habilitação ou Permissão para Dirigir cassada ou suspensa; III - com Carteira Nacional de Habilitação ou Permissão para Dirigir de categoria diferente da do veículo que esteja conduzindo.',
    paragraphsAndIncidents: [
      'Inciso I: Infração gravíssima, 7 pontos, multa 3x, apreensão do veículo.',
      'Inciso II: Infração gravíssima, 7 pontos, multa 3x, recolhimento do documento.',
      'Inciso III: Infração gravíssima, 7 pontos, multa 3x.',
    ],
    practicalApplication: 'Verificar se condutor possuía CNH válida na data, se suspensão/cassação já tinha trânsito em julgado, se categoria compatível.',
    nullityConsequence: 'Nulidade se CNH já regularizada na data ou se notificação de suspensão não entregue (decadência/prescrição).',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022', 'Resolução CONTRAN nº 918/2022'],
  },
  {
    article: 'Art. 163',
    title: 'Entregar veículo a pessoa sem CNH ou com CNH Suspensa/Cassada',
    caput: 'Entregar a direção do veículo a pessoa que não esteja habilitada, com habilitação cassada ou com o direito de dirigir suspenso, ou, ainda, a pessoa que, por seu estado físico ou mental, ou por embriaguez, não esteja em condições de conduzi-lo com segurança.',
    paragraphsAndIncidents: [
      'Infração gravíssima (7 pontos, multa 3x).',
      'Se o condutor não habilitado causar acidente com vítima: crime de trânsito (Art. 309 e 310 CTB).',
    ],
    practicalApplication: 'Proprietário responde solidariamente. Verificar se tinha ciência da condição do condutor.',
    nullityConsequence: 'Nulidade se comprovado que proprietário não tinha como saber da condição.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022'],
  },
  {
    article: 'Art. 180',
    title: 'Licenciamento Anual Obrigatório',
    caput: 'Deixar de efetuar o registro de veículo ou de licenciá-lo no prazo estabelecido pela autoridade de trânsito.',
    paragraphsAndIncidents: [
      'Infração gravíssima (7 pontos, multa 1x), apreensão e remoção do veículo.',
      'Art. 230, V: Transitando com veículo sem o devido licenciamento.',
    ],
    practicalApplication: 'Verificar se CRLV-e disponível, se taxas pagas, se restrição administrativa indevida.',
    nullityConsequence: 'Anulação se licenciamento pago mas sistema não atualizado, ou se notificação não entregue.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022', 'Portaria SENATRAN nº 354/2022'],
  },
  {
    article: 'Art. 195',
    title: 'Transitar em Local/Horário não Permitido',
    caput: 'Transitar em locais e horários não permitidos pela regulamentação estabelecida pela autoridade de trânsito com circunscrição sobre a via:',
    paragraphsAndIncidents: [
      'Inciso I: Em áreas de estacionamento proibido; II: Em ciclovias/ciclofaixas; III: Em acostamentos; IV: Na contramão de direção.',
      'Penalidade: média (4 pts) a grave (5 pts) conforme inciso.',
    ],
    practicalApplication: 'Verificar sinalização (placas R-6, R-45, etc.), horários, se regulamentação publicada e visível.',
    nullityConsequence: 'Anulação se sinalização inexistente, encoberta, ou regulamentação não publicada.',
    relatedResolutions: ['Resolução CONTRAN nº 973/2022 (Sinalização)', 'MBFT 985/2022'],
  },
  {
    article: 'Art. 230',
    title: 'Infrações de Estacionamento e Parada',
    caput: 'Conduzir veículo: V - sem estar licenciado; IX - sem os equipamentos obrigatórios; XVIII - com lotação excedente; XXIII - transitando em ciclovia/ciclofaixa; XXIV - estacionamento em desacordo com sinalização; XXV - parada em desacordo com sinalização.',
    paragraphsAndIncidents: [
      'Inciso V: Gravíssima (7 pts, multa 1x, apreensão); IX: Grave (5 pts); XVIII: Grave (5 pts); XXIII: Média (4 pts); XXIV/XXV: Leve (3 pts) ou Média (4 pts).',
    ],
    practicalApplication: 'Verificar placas R-6a/b/c, R-45, R-46, horários, se área permitia estacionamento/parada, se sinalização visível.',
    nullityConsequence: 'Anulação se sinalização inexistente, irregular, ou equipamento obrigatório presente.',
    relatedResolutions: ['Resolução CONTRAN nº 973/2022', 'MBFT 985/2022'],
  },
  {
    article: 'Art. 231',
    title: 'Transitar sem Equipamentos Obrigatórios',
    caput: 'Conduzir veículo: IX - sem os equipamentos obrigatórios ou estando estes em desacordo com as normas estabelecidas pelo CONTRAN.',
    paragraphsAndIncidents: [
      'Equipamentos: extintor, triângulo, macaco, chave de roda, estepe (conforme tipo), cinto de segurança, encosto de cabeça, tacógrafo (veículos pesados).',
      'Infração grave (5 pontos).',
    ],
    practicalApplication: 'Verificar se equipamento realmente ausente ou em desacordo, se veículo isento (ex: extintor não obrigatório para carros de passeio desde 2015).',
    nullityConsequence: 'Anulação se equipamento não exigido para categoria do veículo, ou se presente mas não identificado pelo agente.',
    relatedResolutions: ['Resolução CONTRAN nº 985/2022 (MBFT)'],
  },
  {
    article: 'Art. 244',
    title: 'Conduzir Motocicleta sem Capacete ou Vestuário',
    caput: 'Conduzir motocicleta, motoneta ou ciclomotor: I - sem usar capacete de segurança com viseira ou óculos de proteção e vestuário de acordo com as normas do CONTRAN; II - transportando passageiro sem capacete ou fora do banco; III - fazendo malabarismo ou equilibrando-se em uma roda; IV - com farol apagado.',
    paragraphsAndIncidents: [
      'Inciso I/II: Gravíssima (7 pts, multa 1x, suspensão do direito de dirigir); III/IV: Gravíssima (7 pts).',
    ],
    practicalApplication: 'Verificar se capacete certificado INMETRO, viseira/óculos, vestuário adequado, farol aceso (obrigatório dia e noite).',
    nullityConsequence: 'Anulação se capacete certificado, farol aceso, ou passageiro em banco próprio com capacete.',
    relatedResolutions: ['Resolução CONTRAN nº 985/2022', 'Portaria INMETRO (capacetes)'],
  },
  {
    article: 'Art. 256',
    title: 'Infrações de Cinto de Segurança e Cadeirinha',
    caput: 'Deixar de usar o cinto de segurança, conforme dispõe o art. 65, ou transportar criança sem observar as normas de segurança (cadeirinha, assento de elevação, bebê conforto).',
    paragraphsAndIncidents: [
      'Inciso I: Condutor sem cinto — Gravíssima (7 pts); II: Passageiro sem cinto — Grave (5 pts); III: Criança sem dispositivo — Gravíssima (7 pts, multa 1x).',
    ],
    practicalApplication: 'Verificar se todos ocupantes usavam cinto, se criança em dispositivo adequado à idade/peso/altura (Res. 819/2021).',
    nullityConsequence: 'Anulação se cinto usado, criança em dispositivo correto, ou veículo isento (ônibus urbano, táxi em algumas cidades).',
    relatedResolutions: ['Resolução CONTRAN nº 819/2021', 'Resolução CONTRAN nº 985/2022'],
  },
  {
    article: 'Art. 265',
    title: 'Dirigir sob Chuva Forte sem Farol Baixo',
    caput: 'Deixar de acender as luzes do veículo: I - à noite; II - em túneis providos de iluminação pública; III - durante o dia, em rodovias, quando houver chuva forte, neblina ou cerração.',
    paragraphsAndIncidents: [
      'Infração média (4 pontos).',
      'Desde 2016 (Lei 13.154): farol baixo obrigatório em rodovias mesmo de dia.',
    ],
    practicalApplication: 'Verificar se condição climática justificava, se em rodovia, se farol realmente apagado.',
    nullityConsequence: 'Anulação se não em rodovia, ou se farol aceso (DRL não conta como farol baixo em alguns entendimentos).',
    relatedResolutions: ['Lei 13.154/2015', 'MBFT 985/2022'],
  },
  {
    article: 'Art. 267',
    title: 'Conversão em Advertência por Escrito (Direito Subjetivo)',
    caput: 'Deverá ser imposta a penalidade de advertência por escrito para as infrações de natureza leve ou média, passíveis de serem punidas com multa, caso o infrator não tenha cometido nenhuma outra infração nos últimos 12 (doze) meses.',
    paragraphsAndIncidents: [
      'Lei 14.071/2020: substituiu "poderá" por "deverá" — direito subjetivo vinculado.',
      'Não se aplica a infrações graves/gravíssimas, nem a reincidentes nos 12 meses.',
    ],
    practicalApplication: 'Para qualquer infração leve (3 pts) ou média (4 pts), condutor sem histórico nos 12 meses tem 100% direito à isenção da multa e cancelamento dos pontos.',
    nullityConsequence: 'Indeferimento ilegal passível de mandado de segurança ou recurso ao CETRAN.',
    relatedResolutions: ['Resolução CONTRAN nº 918/2022, Art. 10', 'Lei 14.071/2020'],
  },
  {
    article: 'Art. 273',
    title: 'Indicação de Condutor Infrator',
    caput: 'Sempre que o condutor for identificado no momento da infração, a autoridade de trânsito consignará essa identificação no auto de infração. Não sendo possível a identificação, o proprietário do veículo será notificado para, no prazo de 15 (quinze) dias contados da notificação, identificar o condutor.',
    paragraphsAndIncidents: [
      '§1º A não indicação no prazo sujeita o proprietário à multa (Gravíssima, 7 pts, multa 1x).',
      '§2º A indicação falsa sujeita às penas de falsidade ideológica.',
      '§7º O condutor indicado responderá pela infração como se fosse o autuado originário.',
    ],
    practicalApplication: 'Prazo de 15 dias da NOTIFICAÇÃO (não do fato). Indicação pode ser eletrônica (SNIE). Verificar se prazo respeitado.',
    nullityConsequence: 'Nulidade da multa por não indicação se prazo não respeitado ou se condutor já identificado no ato.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022', 'Resolução CONTRAN nº 918/2022', 'MBFT 985/2022'],
  },
  {
    article: 'Art. 277',
    title: 'Teste de Etilômetro e Exame Clínico',
    caput: 'Todo condutor de veículo automotor, envolvido em acidente de trânsito ou que for alvo de fiscalização de trânsito, submeter-se-á a teste de etilômetro, exame clínico, perícia ou outro procedimento que permita certificar influência de álcool ou substância psicoativa.',
    paragraphsAndIncidents: [
      'Recusa (Art. 165-A): Gravíssima 10x, suspensão 12 meses.',
      'Resultado ≥ 0,34 mg/L ou 6 dg/L: Crime (Art. 306 CTB).',
      'Resultado > 0,05 mg/L e < 0,34 mg/L: Infração administrativa (Art. 165).',
    ],
    practicalApplication: 'Verificar se etilômetro homologado INMETRO (laudo válido 12 meses), se termo circunstanciado preenchido (Anexo II Res. 432/2013), se oferecido contraprova.',
    nullityConsequence: 'Nulidade se etilômetro sem laudo, termo não preenchido, contraprova negada, ou agente não habilitado.',
    relatedResolutions: ['Resolução CONTRAN nº 432/2013', 'Portaria INMETRO nº 369/2021'],
  },
  {
    article: 'Art. 283',
    title: 'Efeito Suspensivo do Recurso (Garantia)',
    caput: 'O recurso de que trata o art. 285, interposto no prazo legal, tem efeito suspensivo até a decisão final do processo administrativo.',
    paragraphsAndIncidents: [
      'Garantia constitucional de não sofrer restrição antes de julgamento final.',
      'Lei 14.229/2021: Se não julgado em 24 meses, efeito suspensivo de ofício.',
    ],
    practicalApplication: 'Durante recurso à JARI e CETRAN: sem bloqueio no licenciamento, sem restrição na CNH, sem inscrição em dívida ativa.',
    nullityConsequence: 'Qualquer restrição aplicada durante tramitação de recurso tempestivo é nula.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022', 'Lei 14.229/2021'],
  },
  {
    article: 'Art. 284',
    title: 'Prescrição da Pretensão Punitiva',
    caput: 'A pretensão de punir pela infração de trânsito prescreve em 5 (cinco) anos, contados da data do cometimento da infração.',
    paragraphsAndIncidents: [
      'Prescrição intercorrente: 3 (três) anos de paralisação do processo (Lei 9.873/99).',
      'Interrupção: ato inequívoco de impulso processual pela administração.',
    ],
    practicalApplication: 'Verificar se processo paralisado > 3 anos (intercorrente) ou > 5 anos do fato (quinquenal).',
    nullityConsequence: 'Extinção da punibilidade, arquivamento do processo, cancelamento da multa e pontos.',
    relatedResolutions: ['Lei 9.873/1999', 'Resolução CONTRAN nº 900/2022'],
  },
  {
    article: 'Art. 290',
    title: 'Cassação da Carteira Nacional de Habilitação',
    caput: 'A Carteira Nacional de Habilitação será cassada: I - quando o condutor, com o direito de dirigir suspenso, for flagrado conduzindo qualquer veículo; II - em caso de reincidência, no prazo de 12 (doze) meses, das infrações previstas nos arts. 162, I, 163, 164, 165, 173, 174, 175, 244 e 306.',
    paragraphsAndIncidents: [
      'Processo de Cassação (PCDD) — instância mais grave.',
      'Após cassação: 2 anos sem poder tirar nova CNH, necessidade de novo processo de formação.',
    ],
    practicalApplication: 'Verificar se suspensão já tinha trânsito em julgado, se flagrante real, se reincidência em 12 meses comprovada.',
    nullityConsequence: 'Anulação se suspensão não transitada em julgado, ou se reincidência não comprovada no prazo.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022', 'Resolução CONTRAN nº 918/2022'],
  },
  {
    article: 'Art. 306',
    title: 'Crime de Trânsito — Conduzir com Capacidade Psicomotora Alterada',
    caput: 'Conduzir veículo automotor com capacidade psicomotora alterada em razão da influência de álcool ou de outra substância psicoativa que determine dependência.',
    paragraphsAndIncidents: [
      'Pena: detenção 6 meses a 3 anos, multa, suspensão ou proibição de se obter CNH.',
      'Materialidade: etilômetro ≥ 0,34 mg/L OU exame clínico/perícia OU prova testemunhal/vídeo.',
    ],
    practicalApplication: 'Esfera criminal — não julgada no administrativo. Administrativo: Art. 165 (0,05-0,34) ou 165-A (recusa).',
    nullityConsequence: 'Absolvição criminal não anula automaticamente administrativo (esferas independentes), mas prova emprestada pode ser usada.',
    relatedResolutions: ['Resolução CONTRAN nº 432/2013', 'Lei 11.705/2008 (Lei Seca)'],
  },
  {
    article: 'Art. 309',
    title: 'Crime de Trânsito — Dirigir sem Habilitação',
    caput: 'Dirigir veículo automotor, em via pública, sem a devida Permissão para Dirigir ou Carteira de Habilitação ou, ainda, se cassado o direito de dirigir, gerando perigo de dano.',
    paragraphsAndIncidents: [
      'Pena: detenção 6 meses a 1 ano, ou multa.',
      'Perigo de dano presumido (não precisa de acidente).',
    ],
    practicalApplication: 'Esfera criminal. Administrativo: Art. 162 (sem CNH, cassada, suspensa, categoria errada).',
    nullityConsequence: 'Absolvição criminal por atipicidade não impede sanção administrativa (independência das instâncias).',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022'],
  },
  {
    article: 'Art. 310',
    title: 'Crime de Trânsito — Permitir que Pessoa não Habilitada Dirija',
    caput: 'Permitir, confiar ou entregar a direção de veículo automotor a pessoa não habilitada, com habilitação cassada ou com o direito de dirigir suspenso, ou, ainda, a quem, por seu estado físico ou mental, ou por embriaguez, não esteja em condições de conduzi-lo com segurança.',
    paragraphsAndIncidents: [
      'Pena: detenção 6 meses a 1 ano, ou multa.',
      'Proprietário responde se tinha ciência da condição.',
    ],
    practicalApplication: 'Esfera criminal. Administrativo: Art. 163.',
    nullityConsequence: 'Mesma independência entre esferas do Art. 309.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022'],
  },
  {
    article: 'Art. 311',
    title: 'Crime de Trânsito — Afastar-se do Local do Acidente',
    caput: 'Afastar-se o condutor do veículo do local do acidente, para fugir à responsabilidade penal ou civil que lhe possa ser atribuída.',
    paragraphsAndIncidents: [
      'Pena: detenção 6 meses a 1 ano, ou multa.',
      'Não se aplica se para socorrer vítima ou buscar ajuda (em local ermo/sem sinal).',
    ],
    practicalApplication: 'Verificar se condutor permaneceu, prestou socorro, acionou autoridades.',
    nullityConsequence: 'Exclusão de ilicitude se para socorro em local sem comunicação.',
    relatedResolutions: ['Resolução CONTRAN nº 900/2022'],
  },
  {
    article: 'Art. 312',
    title: 'Crime de Trânsito — Entregar Veículo a Pessoa Embriagada',
    caput: 'Entregar a direção de veículo automotor a pessoa embriagada ou sob efeito de substância psicoativa.',
    paragraphsAndIncidents: [
      'Pena: detenção 6 meses a 1 ano, ou multa.',
      'Administrativo: Art. 163, II.',
    ],
    practicalApplication: 'Verificar ciência do proprietário do estado do condutor.',
    nullityConsequence: 'Independência das esferas.',
    relatedResolutions: ['Resolução CONTRAN nº 432/2013'],
  },
];
